//! See <https://www.iana.org/assignments/ipfix/ipfix.xhtml> for more details on fields

use super::data_number::*;

use serde::Serialize;

const CISCO_ENTERPRISE_NUMBER: u32 = 9;
const NETSCALER_ENTERPRISE_NUMBER: u32 = 5951;
const NAT_ENTERPRISE_NUMBER: u32 = 637;
const YAF_ENTERPRISE_NUMBER: u32 = 6871;
const VMWARE_ENTERPRISE_NUMBER: u32 = 6876;
const REVERSE_INFO_ENTERPRISE_NUMBER: u32 = 29305;

#[derive(Debug, Hash, PartialEq, Eq, Clone, Ord, PartialOrd, Copy, Serialize)]
pub enum IPFixField {
    IANA(IANAIPFixField),
    Cisco(CiscoIPFixField),
    Netscaler(NetscalerIPFixField),
    Nat(NatIPFixField),
    Yaf(YafIPFixField),
    VMWare(VMWareIPFixField),
    ReverseInformationElement(ReverseInformationElement),
    Enterprise(u16),
}

impl IPFixField {
    pub fn new(field_type_number: u16, enterprise_number: Option<u32>) -> Self {
        let enterprise_number = match enterprise_number {
            Some(enterprise_number) => enterprise_number,
            None => return IPFixField::IANA(IANAIPFixField::from(field_type_number)),
        };
        match enterprise_number {
            CISCO_ENTERPRISE_NUMBER => {
                IPFixField::Cisco(CiscoIPFixField::from(field_type_number))
            }
            NETSCALER_ENTERPRISE_NUMBER => {
                IPFixField::Netscaler(NetscalerIPFixField::from(field_type_number))
            }
            NAT_ENTERPRISE_NUMBER => IPFixField::Nat(NatIPFixField::from(field_type_number)),
            YAF_ENTERPRISE_NUMBER => IPFixField::Yaf(YafIPFixField::from(field_type_number)),
            VMWARE_ENTERPRISE_NUMBER => {
                IPFixField::VMWare(VMWareIPFixField::from(field_type_number))
            }
            REVERSE_INFO_ENTERPRISE_NUMBER => IPFixField::ReverseInformationElement(
                ReverseInformationElement::from(field_type_number),
            ),
            _ => IPFixField::Enterprise(field_type_number),
        }
    }
}

impl From<IPFixField> for FieldDataType {
    fn from(d: IPFixField) -> FieldDataType {
        match d {
            IPFixField::IANA(field) => field.into(),
            IPFixField::Cisco(field) => field.into(),
            IPFixField::Netscaler(field) => field.into(),
            IPFixField::Nat(field) => field.into(),
            IPFixField::Yaf(field) => field.into(),
            IPFixField::VMWare(field) => field.into(),
            IPFixField::ReverseInformationElement(field) => field.into(),
            IPFixField::Enterprise(_) => FieldDataType::Unknown,
        }
    }
}

macro_rules! ipfix_field_enum {
    (
        $(#[$enum_meta:meta])*
        $vis:vis enum $enum_name:ident {
            $(
                $variant:ident = $value:expr => $field_type:expr
            ),* $(,)?
        }
    ) => {
        $(#[$enum_meta])*
        $vis enum $enum_name {
            $(
                $variant = $value,
            )*
            Unknown(u16),
        }

        impl From<u16> for $enum_name {
            fn from(field_type_number: u16) -> Self {
                match field_type_number {
                    $($value => $enum_name::$variant,)*
                    _ => $enum_name::Unknown(field_type_number),
                }
            }
        }

        impl From<$enum_name> for FieldDataType {
            fn from(field: $enum_name) -> Self {
                match field {
                    $($enum_name::$variant => $field_type,)*
                    $enum_name::Unknown(_) => FieldDataType::Unknown,
                }
            }
        }
    };
}

ipfix_field_enum! {
    #[repr(u16)]
    #[derive(Debug, Hash, PartialEq, Eq, Clone, Ord, PartialOrd, Copy, Serialize)]
    pub enum VMWareIPFixField {
        VmwareTenantProtocol = 880 => FieldDataType::UnsignedDataNumber,
        VmwareTenantSourceIPv4 = 881 => FieldDataType::Ip4Addr,
        VmwareTenantDestIPv4 = 882 => FieldDataType::Ip4Addr,
        VmwareTenantSourceIPv6 = 883 => FieldDataType::Ip6Addr,
        VmwareTenantDestIPv6 = 884 => FieldDataType::Ip6Addr,
        VmwareTenantSourcePort = 886 => FieldDataType::UnsignedDataNumber,
        VmwareTenantDestPort = 887 => FieldDataType::UnsignedDataNumber,
        VmwareEgressInterfaceAttr = 888 => FieldDataType::UnsignedDataNumber,
        VmwareVxlanExportRole = 889 => FieldDataType::UnsignedDataNumber,
        VmwareIngressInterfaceAttr = 890 => FieldDataType::UnsignedDataNumber
    }
}

ipfix_field_enum! {
#[repr(u16)]
#[derive(Debug, Hash, PartialEq, Eq, Clone, Ord, PartialOrd, Copy, Serialize)]
pub enum YafIPFixField {
        InitialTCPFlags = 14 => FieldDataType::UnsignedDataNumber,
        UnionTCPFlags = 15 => FieldDataType::UnsignedDataNumber,
        Payload = 18 => FieldDataType::String,
        ReverseFlowDeltaMilliseconds = 21 => FieldDataType::UnsignedDataNumber,
        SilkAppLabel = 33 => FieldDataType::UnsignedDataNumber,
        PayloadEntropy = 35 => FieldDataType::UnsignedDataNumber,
        OsName = 36 => FieldDataType::String,
        OsVersion = 37 => FieldDataType::String,
        FirstPacketBanner = 38 => FieldDataType::String,
        SecondPacketBanner = 39 => FieldDataType::String,
        FlowAttributes = 40 => FieldDataType::UnsignedDataNumber,
        ExpiredFragmentCount = 100 => FieldDataType::UnsignedDataNumber,
        AssembledFragmentCount = 101 => FieldDataType::UnsignedDataNumber,
        MeanFlowRate = 102 => FieldDataType::UnsignedDataNumber,
        MeanPacketRate = 103 => FieldDataType::UnsignedDataNumber,
        FlowTableFlushEventCount = 104 => FieldDataType::UnsignedDataNumber,
        FlowTablePeakCount = 105 => FieldDataType::UnsignedDataNumber,
        OsFingerPrint = 107 => FieldDataType::String,
        TftpFilename = 126 => FieldDataType::String,
        TftpMode = 127 => FieldDataType::String,
        DnsQueryResponse = 174 => FieldDataType::UnsignedDataNumber,
        DnsQRType = 175 => FieldDataType::UnsignedDataNumber,
        DnsAuthoritative = 176 => FieldDataType::UnsignedDataNumber,
        DnsNXDomain = 177 => FieldDataType::UnsignedDataNumber,
        DnsRRSection = 178 => FieldDataType::UnsignedDataNumber,
        DnsQName = 179 => FieldDataType::String,
        DnsCName = 180 => FieldDataType::String,
        DnsMXPreference = 181 => FieldDataType::UnsignedDataNumber,
        DnsMXExchange = 182 => FieldDataType::String,
        DnsNSDName = 183 => FieldDataType::String,
        DnsPTRDName = 184 => FieldDataType::String,
        SslCipher = 185 => FieldDataType::String,
        SslClientVersion = 186 => FieldDataType::UnsignedDataNumber,
        SslServerCipher = 187 => FieldDataType::UnsignedDataNumber,
        SslCompressionMethod = 188 => FieldDataType::UnsignedDataNumber,
        SslCertVersion = 189 => FieldDataType::UnsignedDataNumber,
        SslCertSignature = 190 => FieldDataType::String,
        DnsTTL = 199 => FieldDataType::UnsignedDataNumber,
        DnsTXTData = 208 => FieldDataType::String,
        DnsSOASerial = 209 => FieldDataType::UnsignedDataNumber,
        DnsSOARefresh = 210 => FieldDataType::UnsignedDataNumber,
        DnsSOARetry = 211 => FieldDataType::UnsignedDataNumber,
        DnsSOAExpire = 212 => FieldDataType::UnsignedDataNumber,
        DnsSOAMinimum = 213 => FieldDataType::UnsignedDataNumber,
        DnsSOAMName = 214 => FieldDataType::String,
        DnsSOARName = 215 => FieldDataType::String,
        DnsSRVPriority = 216 => FieldDataType::UnsignedDataNumber,
        DnsSRVWeight = 217 => FieldDataType::UnsignedDataNumber,
        DnsSRVPort = 218 => FieldDataType::UnsignedDataNumber,
        DnsSRVTarget = 219 => FieldDataType::UnsignedDataNumber,
        TcpUrgTotalCount = 223 => FieldDataType::UnsignedDataNumber,
        DnsID = 226 => FieldDataType::UnsignedDataNumber,
        SslCertSerialNumber = 244 => FieldDataType::String,
        SslObjectType = 245 => FieldDataType::String,
        SslObjectValue = 246 => FieldDataType::String,
        SslCertValidityNotBefore = 247 => FieldDataType::String,
        SslCertValidityNotAfter = 248 => FieldDataType::String,
        SslPublicKeyAlgorithm = 249 => FieldDataType::String,
        SslPublicKeyLength = 250 => FieldDataType::String,
        RtpPayloadType = 287 => FieldDataType::UnsignedDataNumber,
        ReverseRtpPayloadType = 288 => FieldDataType::UnsignedDataNumber,
        MptcpInitialDataSequenceNumber = 289 => FieldDataType::UnsignedDataNumber,
        MptcpReceiverToken = 290 => FieldDataType::UnsignedDataNumber,
        MptcpMaximumSegmentSize = 291 => FieldDataType::UnsignedDataNumber,
        MptcpAddressID = 292 => FieldDataType::UnsignedDataNumber,
        MptcpFlags = 293 => FieldDataType::UnsignedDataNumber,
        SslServerName = 294 => FieldDataType::String,
        SslCertificateHash = 295 => FieldDataType::String,
        SmallPacketCount = 500 => FieldDataType::UnsignedDataNumber,
        NonEmptyPacketCount = 501 => FieldDataType::UnsignedDataNumber,
        DataByteCount = 502 => FieldDataType::UnsignedDataNumber,
        AverageInterarrivalTime = 503 => FieldDataType::UnsignedDataNumber,
        StandardDeviationInterarrivalTime = 504 => FieldDataType::UnsignedDataNumber,
        FirstNonEmptyPacketSize = 505 => FieldDataType::UnsignedDataNumber,
        MaxPacketSize = 506 => FieldDataType::UnsignedDataNumber,
        FirstEightNonEmptyPacketDirections = 507 => FieldDataType::UnsignedDataNumber,
        StandardDeviationPayloadLength = 508 => FieldDataType::UnsignedDataNumber,
        LargePacketCount = 510 => FieldDataType::UnsignedDataNumber,
        ReverseInitialTCPFlags = 16398 => FieldDataType::UnsignedDataNumber,
        ReverseUnionTCPFlags = 16399 => FieldDataType::UnsignedDataNumber,
        ReversePayload = 16402 => FieldDataType::String,
        ReversePayloadEntropy = 16419 => FieldDataType::UnsignedDataNumber,
        ReverseOsName = 16420 => FieldDataType::String,
        ReverseOsVersion = 16421 => FieldDataType::String,
        ReverseFirstPacketBanner = 16422 => FieldDataType::String,
        ReverseSecondPacketBanner = 16423 => FieldDataType::String,
        ReverseFlowAttributes = 16424 => FieldDataType::UnsignedDataNumber,
        ReverseOsFingerPrint = 16491 => FieldDataType::String,
        ReverseSmallPacketCount = 16884 => FieldDataType::UnsignedDataNumber,
        ReverseNonEmptyPacketCount = 16885 => FieldDataType::UnsignedDataNumber,
        ReverseDataByteCount = 16886 => FieldDataType::UnsignedDataNumber,
        ReverseAverageInterarrivalTime = 16887 => FieldDataType::UnsignedDataNumber,
        ReverseStandardDeviationInterarrivalTime = 16888 => FieldDataType::UnsignedDataNumber,
        ReverseFirstNonEmptyPacketSize = 16889 => FieldDataType::UnsignedDataNumber,
        ReverseMaxPacketSize = 16890 => FieldDataType::UnsignedDataNumber,
        ReverseStandardDeviationPayloadLength = 16892 => FieldDataType::UnsignedDataNumber,
        ReverseLargePacketCount = 16894 => FieldDataType::UnsignedDataNumber
    }
}

ipfix_field_enum! {
#[repr(u16)]
#[derive(Debug, Hash, PartialEq, Eq, Clone, Ord, PartialOrd, Copy, Serialize)]
    pub enum NetscalerIPFixField {
    NetscalerRoundTripTime = 128 => FieldDataType::UnsignedDataNumber,
    NetscalerTransactionId = 129 => FieldDataType::UnsignedDataNumber,
    NetscalerHttpReqUrl = 130 => FieldDataType::String,
    NetscalerHttpReqCookie = 131 => FieldDataType::String,
    NetscalerFlowFlags = 132 => FieldDataType::UnsignedDataNumber,
    NetscalerConnectionId = 133 => FieldDataType::UnsignedDataNumber,
    NetscalerSyslogPriority = 134 => FieldDataType::UnsignedDataNumber,
    NetscalerSyslogMessage = 135 => FieldDataType::String,
    NetscalerSyslogTimestamp = 136 => FieldDataType::UnsignedDataNumber,
    NetscalerHttpReqReferer = 140 => FieldDataType::String,
    NetscalerHttpReqMethod = 141 => FieldDataType::String,
    NetscalerHttpReqHost = 142 => FieldDataType::String,
    NetscalerHttpReqUserAgent = 143 => FieldDataType::String,
    NetscalerHttpRspStatus = 144 => FieldDataType::UnsignedDataNumber,
    NetscalerHttpRspLen = 145 => FieldDataType::UnsignedDataNumber,
    NetscalerServerTTFB = 146 => FieldDataType::UnsignedDataNumber,
    NetscalerServerTTLB = 147 => FieldDataType::UnsignedDataNumber,
    NetscalerAppNameIncarnationNumber = 150 => FieldDataType::UnsignedDataNumber,
    NetscalerAppNameAppId = 151 => FieldDataType::UnsignedDataNumber,
    NetscalerAppName = 152 => FieldDataType::String,
    NetscalerHttpReqRcvFB = 153 => FieldDataType::UnsignedDataNumber,
    NetscalerHttpReqForwFB = 156 => FieldDataType::UnsignedDataNumber,
    NetscalerHttpResRcvFB = 157 => FieldDataType::UnsignedDataNumber,
    NetscalerHttpResForwFB = 158 => FieldDataType::UnsignedDataNumber,
    NetscalerHttpReqRcvLB = 159 => FieldDataType::UnsignedDataNumber,
    NetscalerHttpReqForwLB = 160 => FieldDataType::UnsignedDataNumber,
    NetscalerMainPageId = 161 => FieldDataType::UnsignedDataNumber,
    NetscalerMainPageCoreId = 162 => FieldDataType::UnsignedDataNumber,
    NetscalerHttpClientInteractionStartTime = 163 => FieldDataType::String,
    NetscalerHttpClientRenderEndTime = 164 => FieldDataType::String,
    NetscalerHttpClientRenderStartTime = 165 => FieldDataType::String,
    NetscalerAppTemplateName = 167 => FieldDataType::String,
    NetscalerHttpClientInteractionEndTime = 168 => FieldDataType::String,
    NetscalerHttpResRcvLB = 169 => FieldDataType::UnsignedDataNumber,
    NetscalerHttpResForwLB = 170 => FieldDataType::UnsignedDataNumber,
    NetscalerAppUnitNameAppId = 171 => FieldDataType::UnsignedDataNumber,
    NetscalerDbLoginFlags = 172 => FieldDataType::UnsignedDataNumber,
    NetscalerDbReqType = 173 => FieldDataType::UnsignedDataNumber,
    NetscalerDbProtocolName = 174 => FieldDataType::UnsignedDataNumber,
    NetscalerDbUserName = 175 => FieldDataType::String,
    NetscalerDbDatabaseName = 176 => FieldDataType::String,
    NetscalerDbCltHostName = 177 => FieldDataType::String,
    NetscalerDbReqString = 178 => FieldDataType::String,
    NetscalerDbRespStatusString = 179 => FieldDataType::String,
    NetscalerDbRespStatus = 180 => FieldDataType::UnsignedDataNumber,
    NetscalerDbRespLength = 181 => FieldDataType::UnsignedDataNumber,
    NetscalerClientRTT = 182 => FieldDataType::UnsignedDataNumber,
    NetscalerHttpContentType = 183 => FieldDataType::String,
    NetscalerHttpReqAuthorization = 185 => FieldDataType::String,
    NetscalerHttpReqVia = 186 => FieldDataType::String,
    NetscalerHttpResLocation = 187 => FieldDataType::String,
    NetscalerHttpResSetCookie = 188 => FieldDataType::String,
    NetscalerHttpResSetCookie2 = 189 => FieldDataType::String,
    NetscalerHttpReqXForwardedFor = 190 => FieldDataType::String,
    NetscalerConnectionChainID = 192 => FieldDataType::Vec,
    NetscalerConnectionChainHopCount = 193 => FieldDataType::UnsignedDataNumber,
    NetscalerICASessionGuid = 200 => FieldDataType::Vec,
    NetscaleIcaClientVersion = 201 => FieldDataType::String,
    NetscalerIcaClientType = 202 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaClientIP = 203 => FieldDataType::Ip4Addr,
    NetscalerIcaClientHostName = 204 => FieldDataType::String,
    NetscalerAaaUsername = 205 => FieldDataType::String,
    NetscalerIcaDomainName = 207 => FieldDataType::String,
    NetscalerIcaClientLauncher = 208 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaSessionSetupTime = 209 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaServerName = 210 => FieldDataType::String,
    NetscalerIcaSessionReconnects = 214 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaRTT = 215 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaClientsideRXBytes = 216 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaClientsideTXBytes = 217 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaClientsidePacketsRetransmit = 219 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaServersidePacketsRetransmit = 220 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaClientsideRTT = 221 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaServersideRTT = 222 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaSessionUpdateBeginSec = 223 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaSessionUpdateEndSec = 224 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaChannelId1 = 225 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaChannelId1Bytes = 226 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaChannelId2 = 227 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaChannelId2Bytes = 228 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaChannelId3 = 229 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaChannelId3Bytes = 230 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaChannelId4 = 231 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaChannelId4Bytes = 232 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaChannelId5 = 233 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaChannelId5Bytes = 234 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaConnectionPriority = 235 => FieldDataType::UnsignedDataNumber,
    NetscalerApplicationStartupDuration = 236 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaLaunchMechanism = 237 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaApplicationName = 238 => FieldDataType::String,
    NetscalerApplicationStartupTime = 239 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaApplicationTerminationType = 240 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaApplicationTerminationTime = 241 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaSessionEndTime = 242 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaClientsideJitter = 243 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaServersideJitter = 244 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaAppProcessID = 245 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaAppModulePath = 246 => FieldDataType::String,
    NetscalerIcaDeviceSerialNo = 247 => FieldDataType::UnsignedDataNumber,
    NetscalerMsiClientCookie = 248 => FieldDataType::Vec,
    NetscalerIcaFlags = 249 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaUsername = 250 => FieldDataType::String,
    NetscalerLicenseType = 251 => FieldDataType::UnsignedDataNumber,
    NetscalerMaxLicenseCount = 252 => FieldDataType::UnsignedDataNumber,
    NetscalerCurrentLicenseConsumed = 253 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaNetworkUpdateStartTime = 254 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaNetworkUpdateEndTime = 255 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaClientsideSRTT = 256 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaServersideSRTT = 257 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaClientsideDelay = 258 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaServersideDelay = 259 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaHostDelay = 260 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaClientSideWindowSize = 261 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaServerSideWindowSize = 262 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaClientSideRTOCount = 263 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaServerSideRTOCount = 264 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaL7ClientLatency = 265 => FieldDataType::UnsignedDataNumber,
    NetscalerIcaL7ServerLatency = 266 => FieldDataType::UnsignedDataNumber,
    NetscalerHttpDomainName = 267 => FieldDataType::String,
    NetscalerCacheRedirClientConnectionCoreID = 268 => FieldDataType::UnsignedDataNumber,
    NetscalerCacheRedirClientConnectionTransactionID = 269 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown270 = 270 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown271 = 271 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown272 = 272 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown273 = 273 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown274 = 274 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown275 = 275 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown276 = 276 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown277 = 277 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown278 = 278 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown279 = 279 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown280 = 280 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown281 = 281 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown282 = 282 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown283 = 283 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown284 = 284 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown285 = 285 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown286 = 286 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown287 = 287 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown288 = 288 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown289 = 289 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown290 = 290 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown291 = 291 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown292 = 292 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown293 = 293 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown294 = 294 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown295 = 295 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown296 = 296 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown297 = 297 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown298 = 298 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown299 = 299 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown300 = 300 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown301 = 301 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown302 = 302 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown303 = 303 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown304 = 304 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown305 = 305 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown306 = 306 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown307 = 307 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown308 = 308 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown309 = 309 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown310 = 310 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown311 = 311 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown312 = 312 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown313 = 313 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown314 = 314 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown315 = 315 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown316 = 316 => FieldDataType::String,
    NetscalerUnknown317 = 317 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown318 = 318 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown319 = 319 => FieldDataType::String,
    NetscalerUnknown320 = 320 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown321 = 321 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown322 = 322 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown323 = 323 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown324 = 324 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown325 = 325 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown326 = 326 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown327 = 327 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown328 = 328 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown329 = 329 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown330 = 330 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown331 = 331 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown332 = 332 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown333 = 333 => FieldDataType::String,
    NetscalerUnknown334 = 334 => FieldDataType::String,
    NetscalerUnknown335 = 335 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown336 = 336 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown337 = 337 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown338 = 338 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown339 = 339 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown340 = 340 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown341 = 341 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown342 = 342 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown343 = 343 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown344 = 344 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown345 = 345 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown346 = 346 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown347 = 347 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown348 = 348 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown349 = 349 => FieldDataType::String,
    NetscalerUnknown350 = 350 => FieldDataType::String,
    NetscalerUnknown351 = 351 => FieldDataType::String,
    NetscalerUnknown352 = 352 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown353 = 353 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown354 = 354 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown355 = 355 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown356 = 356 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown357 = 357 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown358 = 358 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown359 = 359 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown360 = 360 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown361 = 361 => FieldDataType::Vec,
    NetscalerUnknown362 = 362 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown363 = 363 => FieldDataType::Vec,
    NetscalerUnknown364 = 364 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown365 = 365 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown366 = 366 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown367 = 367 => FieldDataType::Vec,
    NetscalerUnknown377 = 377 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown380 = 380 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown383 = 383 => FieldDataType::Vec,
    NetscalerUnknown384 = 384 => FieldDataType::Vec,
    NetscalerUnknown385 = 385 => FieldDataType::Vec,
    NetscalerUnknown386 = 386 => FieldDataType::String,
    NetscalerUnknown387 = 387 => FieldDataType::String,
    NetscalerUnknown388 = 388 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown389 = 389 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown391 = 391 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown392 = 392 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown393 = 393 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown394 = 394 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown398 = 398 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown399 = 399 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown400 = 400 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown401 = 401 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown402 = 402 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown403 = 403 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown404 = 404 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown405 = 405 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown408 = 408 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown427 = 427 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown429 = 429 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown432 = 432 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown433 = 433 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown434 = 434 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown435 = 435 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown447 = 447 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown448 = 448 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown451 = 451 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown452 = 452 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown453 = 453 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown455 = 455 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown458 = 458 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown459 = 459 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown460 = 460 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown461 = 461 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown463 = 463 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown464 = 464 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown465 = 465 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown466 = 466 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown467 = 467 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown468 = 468 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown475 = 475 => FieldDataType::String,
    NetscalerUnknown476 = 476 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown477 = 477 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown478 = 478 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown479 = 479 => FieldDataType::String,
    NetscalerUnknown480 = 480 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown481 = 481 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown487 = 487 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown488 = 488 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown489 = 489 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown491 = 491 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown492 = 492 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown493 = 493 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown494 = 494 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown507 = 507 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown508 = 508 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown509 = 509 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown510 = 510 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown511 = 511 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown512 = 512 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown513 = 513 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown514 = 514 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown518 = 518 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown519 = 519 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown520 = 520 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown521 = 521 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown522 = 522 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown523 = 523 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown532 = 532 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown533 = 533 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown534 = 534 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown535 = 535 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown536 = 536 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown537 = 537 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown538 = 538 => FieldDataType::UnsignedDataNumber,
    NetscalerUnknown541 = 541 => FieldDataType::UnsignedDataNumber,
    }
}

ipfix_field_enum! {
#[repr(u16)]
#[derive(Debug, Hash, PartialEq, Eq, Clone, Ord, PartialOrd, Copy, Serialize)]
    pub enum NatIPFixField {
    NatInsideSvcid = 91 => FieldDataType::UnsignedDataNumber,
    NatOutsideSvcid = 92 => FieldDataType::UnsignedDataNumber,
    NatSubString = 93 => FieldDataType::String,
    }
}

ipfix_field_enum! {
#[repr(u16)]
#[derive(Debug, Hash, PartialEq, Eq, Clone, Ord, PartialOrd, Copy, Serialize)]
    pub enum CiscoIPFixField {
        CiscoServerBytesNetwork = 8337 => FieldDataType::UnsignedDataNumber,
        CiscoClientBytesNetwork = 8338 => FieldDataType::UnsignedDataNumber,
        CiscoServicesWaasSegment = 9252 => FieldDataType::UnsignedDataNumber,
        CiscoServicesWaasPassthroughReason = 9253 => FieldDataType::UnsignedDataNumber,
        CiscoAppHttpUriStatistics = 9357 => FieldDataType::String,
        CiscoAppCategoryName = 12232 => FieldDataType::String,
        CiscoAppGroupName = 12234 => FieldDataType::String,
        CiscoAppHttpHost = 12235 => FieldDataType::String,
        CiscoClientIpv4Address = 12236 => FieldDataType::Ip4Addr,
        CiscoServerIpv4Address = 12237 => FieldDataType::Ip4Addr,
        CiscoClientL4Port = 12240 => FieldDataType::UnsignedDataNumber,
        CiscoServerL4Port = 12241 => FieldDataType::UnsignedDataNumber,
        CiscoConnectionId = 12242 => FieldDataType::UnsignedDataNumber,
        CiscoAppBusiness = 12244 => FieldDataType::String,
    }
}

ipfix_field_enum! {
    #[repr(u16)]
    #[derive(Debug, Hash, PartialEq, Eq, Clone, Ord, PartialOrd, Copy, Serialize)]
    pub enum ReverseInformationElement {
    // This enum is generated from the YAML-like mapping above.
    // Only the field numbers and names are used, types are mapped to FieldDataType in the macro.
    ReverseOctetDeltaCount = 1 => FieldDataType::UnsignedDataNumber,
    ReversePacketDeltaCount = 2 => FieldDataType::UnsignedDataNumber,
    ReverseDeltaFlowCount = 3 => FieldDataType::UnsignedDataNumber,
    ReverseProtocolIdentifier = 4 => FieldDataType::UnsignedDataNumber,
    ReverseIpClassOfService = 5 => FieldDataType::UnsignedDataNumber,
    ReverseTcpControlBits = 6 => FieldDataType::UnsignedDataNumber,
    ReverseSourceTransportPort = 7 => FieldDataType::UnsignedDataNumber,
    ReverseSourceIPv4Address = 8 => FieldDataType::Ip4Addr,
    ReverseSourceIPv4PrefixLength = 9 => FieldDataType::UnsignedDataNumber,
    ReverseIngressInterface = 10 => FieldDataType::UnsignedDataNumber,
    ReverseDestinationTransportPort = 11 => FieldDataType::UnsignedDataNumber,
    ReverseDestinationIPv4Address = 12 => FieldDataType::Ip4Addr,
    ReverseDestinationIPv4PrefixLength = 13 => FieldDataType::UnsignedDataNumber,
    ReverseEgressInterface = 14 => FieldDataType::UnsignedDataNumber,
    ReverseIpNextHopIPv4Address = 15 => FieldDataType::Ip4Addr,
    ReverseBgpSourceAsNumber = 16 => FieldDataType::UnsignedDataNumber,
    ReverseBgpDestinationAsNumber = 17 => FieldDataType::UnsignedDataNumber,
    ReverseBgpNextHopIPv4Address = 18 => FieldDataType::Ip4Addr,
    ReversePostMCastPacketDeltaCount = 19 => FieldDataType::UnsignedDataNumber,
    ReversePostMCastOctetDeltaCount = 20 => FieldDataType::UnsignedDataNumber,
    ReverseFlowEndSysUpTime = 21 => FieldDataType::UnsignedDataNumber,
    ReverseFlowStartSysUpTime = 22 => FieldDataType::UnsignedDataNumber,
    ReversePostOctetDeltaCount = 23 => FieldDataType::UnsignedDataNumber,
    ReversePostPacketDeltaCount = 24 => FieldDataType::UnsignedDataNumber,
    ReverseMinimumIpTotalLength = 25 => FieldDataType::UnsignedDataNumber,
    ReverseMaximumIpTotalLength = 26 => FieldDataType::UnsignedDataNumber,
    ReverseSourceIPv6Address = 27 => FieldDataType::Ip6Addr,
    ReverseDestinationIPv6Address = 28 => FieldDataType::Ip6Addr,
    ReverseSourceIPv6PrefixLength = 29 => FieldDataType::UnsignedDataNumber,
    ReverseDestinationIPv6PrefixLength = 30 => FieldDataType::UnsignedDataNumber,
    ReverseFlowLabelIPv6 = 31 => FieldDataType::UnsignedDataNumber,
    ReverseIcmpTypeCodeIPv4 = 32 => FieldDataType::UnsignedDataNumber,
    ReverseIgmpType = 33 => FieldDataType::UnsignedDataNumber,
    ReverseSamplingInterval = 34 => FieldDataType::UnsignedDataNumber,
    ReverseSamplingAlgorithm = 35 => FieldDataType::UnsignedDataNumber,
    ReverseFlowActiveTimeout = 36 => FieldDataType::UnsignedDataNumber,
    ReverseFlowIdleTimeout = 37 => FieldDataType::UnsignedDataNumber,
    ReverseEngineType = 38 => FieldDataType::UnsignedDataNumber,
    ReverseEngineId = 39 => FieldDataType::UnsignedDataNumber,
    ReverseIpv4RouterSc = 43 => FieldDataType::Ip4Addr,
    ReverseSourceIPv4Prefix = 44 => FieldDataType::Ip4Addr,
    ReverseDestinationIPv4Prefix = 45 => FieldDataType::Ip4Addr,
    ReverseMplsTopLabelType = 46 => FieldDataType::UnsignedDataNumber,
    ReverseMplsTopLabelIPv4Address = 47 => FieldDataType::Ip4Addr,
    ReverseSamplerId = 48 => FieldDataType::UnsignedDataNumber,
    ReverseSamplerMode = 49 => FieldDataType::UnsignedDataNumber,
    ReverseSamplerRandomInterval = 50 => FieldDataType::UnsignedDataNumber,
    ReverseClassId = 51 => FieldDataType::UnsignedDataNumber,
    ReverseMinimumTTL = 52 => FieldDataType::UnsignedDataNumber,
    ReverseMaximumTTL = 53 => FieldDataType::UnsignedDataNumber,
    ReverseFragmentIdentification = 54 => FieldDataType::UnsignedDataNumber,
    ReversePostIpClassOfService = 55 => FieldDataType::UnsignedDataNumber,
    ReverseSourceMacAddress = 56 => FieldDataType::MacAddr,
    ReversePostDestinationMacAddress = 57 => FieldDataType::MacAddr,
    ReverseVlanId = 58 => FieldDataType::UnsignedDataNumber,
    ReversePostVlanId = 59 => FieldDataType::UnsignedDataNumber,
    ReverseIpVersion = 60 => FieldDataType::UnsignedDataNumber,
    ReverseFlowDirection = 61 => FieldDataType::UnsignedDataNumber,
    ReverseIpNextHopIPv6Address = 62 => FieldDataType::Ip6Addr,
    ReverseBgpNextHopIPv6Address = 63 => FieldDataType::Ip6Addr,
    ReverseIpv6ExtensionHeaders = 64 => FieldDataType::UnsignedDataNumber,
    ReverseMplsTopLabelStackSection = 70 => FieldDataType::String,
    ReverseMplsLabelStackSection2 = 71 => FieldDataType::String,
    ReverseMplsLabelStackSection3 = 72 => FieldDataType::String,
    ReverseMplsLabelStackSection4 = 73 => FieldDataType::String,
    ReverseMplsLabelStackSection5 = 74 => FieldDataType::String,
    ReverseMplsLabelStackSection6 = 75 => FieldDataType::String,
    ReverseMplsLabelStackSection7 = 76 => FieldDataType::String,
    ReverseMplsLabelStackSection8 = 77 => FieldDataType::String,
    ReverseMplsLabelStackSection9 = 78 => FieldDataType::String,
    ReverseMplsLabelStackSection10 = 79 => FieldDataType::String,
    ReverseDestinationMacAddress = 80 => FieldDataType::MacAddr,
    ReversePostSourceMacAddress = 81 => FieldDataType::MacAddr,
    ReverseInterfaceName = 82 => FieldDataType::String,
    ReverseInterfaceDescription = 83 => FieldDataType::String,
    ReverseSamplerName = 84 => FieldDataType::String,
    ReverseOctetTotalCount = 85 => FieldDataType::UnsignedDataNumber,
    ReversePacketTotalCount = 86 => FieldDataType::UnsignedDataNumber,
    ReverseFlagsAndSamplerId = 87 => FieldDataType::UnsignedDataNumber,
    ReverseFragmentOffset = 88 => FieldDataType::UnsignedDataNumber,
    ReverseForwardingStatus = 89 => FieldDataType::UnsignedDataNumber,
    ReverseMplsVpnRouteDistinguisher = 90 => FieldDataType::String,
    ReverseMplsTopLabelPrefixLength = 91 => FieldDataType::UnsignedDataNumber,
    ReverseSrcTrafficIndex = 92 => FieldDataType::UnsignedDataNumber,
    ReverseDstTrafficIndex = 93 => FieldDataType::UnsignedDataNumber,
    ReverseApplicationDescription = 94 => FieldDataType::String,
    ReverseApplicationId = 95 => FieldDataType::String,
    ReverseApplicationName = 96 => FieldDataType::String,
    ReversePostIpDiffServCodePoint = 98 => FieldDataType::UnsignedDataNumber,
    ReverseMulticastReplicationFactor = 99 => FieldDataType::UnsignedDataNumber,
    ReverseClassName = 100 => FieldDataType::String,
    ReverseClassificationEngineId = 101 => FieldDataType::UnsignedDataNumber,
    ReverseLayer2packetSectionOffset = 102 => FieldDataType::UnsignedDataNumber,
    ReverseLayer2packetSectionSize = 103 => FieldDataType::UnsignedDataNumber,
    ReverseLayer2packetSectionData = 104 => FieldDataType::String,
    ReverseBgpNextAdjacentAsNumber = 128 => FieldDataType::UnsignedDataNumber,
    ReverseBgpPrevAdjacentAsNumber = 129 => FieldDataType::UnsignedDataNumber,
    ReverseDroppedOctetDeltaCount = 132 => FieldDataType::UnsignedDataNumber,
    ReverseDroppedPacketDeltaCount = 133 => FieldDataType::UnsignedDataNumber,
    ReverseDroppedOctetTotalCount = 134 => FieldDataType::UnsignedDataNumber,
    ReverseDroppedPacketTotalCount = 135 => FieldDataType::UnsignedDataNumber,
    ReverseFlowEndReason = 136 => FieldDataType::UnsignedDataNumber,
    ReverseObservationPointId = 138 => FieldDataType::UnsignedDataNumber,
    ReverseIcmpTypeCodeIPv6 = 139 => FieldDataType::UnsignedDataNumber,
    ReverseMplsTopLabelIPv6Address = 140 => FieldDataType::Ip6Addr,
    ReverseLineCardId = 141 => FieldDataType::UnsignedDataNumber,
    ReversePortId = 142 => FieldDataType::UnsignedDataNumber,
    ReverseMeteringProcessId = 143 => FieldDataType::UnsignedDataNumber,
    ReverseExportingProcessId = 144 => FieldDataType::UnsignedDataNumber,
    ReverseWlanChannelId = 146 => FieldDataType::UnsignedDataNumber,
    ReverseWlanSSID = 147 => FieldDataType::String,
    ReverseFlowStartSeconds = 150 => FieldDataType::UnsignedDataNumber,
    ReverseFlowEndSeconds = 151 => FieldDataType::UnsignedDataNumber,
    ReverseFlowStartMilliseconds = 152 => FieldDataType::UnsignedDataNumber,
    ReverseFlowEndMilliseconds = 153 => FieldDataType::UnsignedDataNumber,
    ReverseFlowStartMicroseconds = 154 => FieldDataType::UnsignedDataNumber,
    ReverseFlowEndMicroseconds = 155 => FieldDataType::UnsignedDataNumber,
    ReverseFlowStartNanoseconds = 156 => FieldDataType::UnsignedDataNumber,
    ReverseFlowEndNanoseconds = 157 => FieldDataType::UnsignedDataNumber,
    ReverseFlowStartDeltaMicroseconds = 158 => FieldDataType::UnsignedDataNumber,
    ReverseFlowEndDeltaMicroseconds = 159 => FieldDataType::UnsignedDataNumber,
    ReverseSystemInitTimeMilliseconds = 160 => FieldDataType::UnsignedDataNumber,
    ReverseFlowDurationMilliseconds = 161 => FieldDataType::UnsignedDataNumber,
    ReverseFlowDurationMicroseconds = 162 => FieldDataType::UnsignedDataNumber,
    ReverseDestinationIPv6Prefix = 169 => FieldDataType::Ip6Addr,
    ReverseSourceIPv6Prefix = 170 => FieldDataType::Ip6Addr,
    ReversePostOctetTotalCount = 171 => FieldDataType::UnsignedDataNumber,
    ReversePostPacketTotalCount = 172 => FieldDataType::UnsignedDataNumber,
    ReversePostMCastPacketTotalCount = 174 => FieldDataType::UnsignedDataNumber,
    ReversePostMCastOctetTotalCount = 175 => FieldDataType::UnsignedDataNumber,
    ReverseIcmpTypeIPv4 = 176 => FieldDataType::UnsignedDataNumber,
    ReverseIcmpCodeIPv4 = 177 => FieldDataType::UnsignedDataNumber,
    ReverseIcmpTypeIPv6 = 178 => FieldDataType::UnsignedDataNumber,
    ReverseIcmpCodeIPv6 = 179 => FieldDataType::UnsignedDataNumber,
    ReverseUdpSourcePort = 180 => FieldDataType::UnsignedDataNumber,
    ReverseUdpDestinationPort = 181 => FieldDataType::UnsignedDataNumber,
    ReverseTcpSourcePort = 182 => FieldDataType::UnsignedDataNumber,
    ReverseTcpDestinationPort = 183 => FieldDataType::UnsignedDataNumber,
    ReverseTcpSequenceNumber = 184 => FieldDataType::UnsignedDataNumber,
    ReverseTcpAcknowledgementNumber = 185 => FieldDataType::UnsignedDataNumber,
    ReverseTcpWindowSize = 186 => FieldDataType::UnsignedDataNumber,
    ReverseTcpUrgentPointer = 187 => FieldDataType::UnsignedDataNumber,
    ReverseTcpHeaderLength = 188 => FieldDataType::UnsignedDataNumber,
    ReverseIpHeaderLength = 189 => FieldDataType::UnsignedDataNumber,
    ReverseTotalLengthIPv4 = 190 => FieldDataType::UnsignedDataNumber,
    ReversePayloadLengthIPv6 = 191 => FieldDataType::UnsignedDataNumber,
    ReverseIpTTL = 192 => FieldDataType::UnsignedDataNumber,
    ReverseNextHeaderIPv6 = 193 => FieldDataType::UnsignedDataNumber,
    ReverseMplsPayloadLength = 194 => FieldDataType::UnsignedDataNumber,
    ReverseIpDiffServCodePoint = 195 => FieldDataType::UnsignedDataNumber,
    ReverseIpPrecedence = 196 => FieldDataType::UnsignedDataNumber,
    ReverseFragmentFlags = 197 => FieldDataType::UnsignedDataNumber,
    ReverseOctetDeltaSumOfSquares = 198 => FieldDataType::UnsignedDataNumber,
    ReverseOctetTotalSumOfSquares = 199 => FieldDataType::UnsignedDataNumber,
    ReverseMplsTopLabelTTL = 200 => FieldDataType::UnsignedDataNumber,
    ReverseMplsLabelStackLength = 201 => FieldDataType::UnsignedDataNumber,
    ReverseMplsLabelStackDepth = 202 => FieldDataType::UnsignedDataNumber,
    ReverseMplsTopLabelExp = 203 => FieldDataType::UnsignedDataNumber,
    ReverseIpPayloadLength = 204 => FieldDataType::UnsignedDataNumber,
    ReverseUdpMessageLength = 205 => FieldDataType::UnsignedDataNumber,
    ReverseIsMulticast = 206 => FieldDataType::UnsignedDataNumber,
    ReverseIpv4IHL = 207 => FieldDataType::UnsignedDataNumber,
    ReverseIpv4Options = 208 => FieldDataType::UnsignedDataNumber,
    ReverseTcpOptions = 209 => FieldDataType::UnsignedDataNumber,
    ReverseTcpSynTotalCount = 218 => FieldDataType::UnsignedDataNumber,
    ReverseTcpFinTotalCount = 219 => FieldDataType::UnsignedDataNumber,
    ReverseTcpRstTotalCount = 220 => FieldDataType::UnsignedDataNumber,
    ReverseTcpPshTotalCount = 221 => FieldDataType::UnsignedDataNumber,
    ReverseTcpAckTotalCount = 222 => FieldDataType::UnsignedDataNumber,
    ReverseTcpUrgTotalCount = 223 => FieldDataType::UnsignedDataNumber,
    ReverseIpTotalLength = 224 => FieldDataType::UnsignedDataNumber,
    ReversePostNATSourceIPv4Address = 225 => FieldDataType::Ip4Addr,
    ReversePostNATDestinationIPv4Address = 226 => FieldDataType::Ip4Addr,
    ReversePostNAPTSourceTransportPort = 227 => FieldDataType::UnsignedDataNumber,
    ReversePostNAPTDestinationTransportPort = 228 => FieldDataType::UnsignedDataNumber,
    ReverseNatOriginatingAddressRealm = 229 => FieldDataType::UnsignedDataNumber,
    ReverseNatEvent = 230 => FieldDataType::UnsignedDataNumber,
    ReverseInitiatorOctets = 231 => FieldDataType::UnsignedDataNumber,
    ReverseResponderOctets = 232 => FieldDataType::UnsignedDataNumber,
    ReverseFirewallEvent = 233 => FieldDataType::UnsignedDataNumber,
    ReverseIngressVRFID = 234 => FieldDataType::UnsignedDataNumber,
    ReverseEgressVRFID = 235 => FieldDataType::UnsignedDataNumber,
    ReverseVRFname = 236 => FieldDataType::String,
    ReversePostMplsTopLabelExp = 237 => FieldDataType::UnsignedDataNumber,
    ReverseTcpWindowScale = 238 => FieldDataType::UnsignedDataNumber,
    ReverseEthernetHeaderLength = 240 => FieldDataType::UnsignedDataNumber,
    ReverseEthernetPayloadLength = 241 => FieldDataType::UnsignedDataNumber,
    ReverseEthernetTotalLength = 242 => FieldDataType::UnsignedDataNumber,
    ReverseDot1qVlanId = 243 => FieldDataType::UnsignedDataNumber,
    ReverseDot1qPriority = 244 => FieldDataType::UnsignedDataNumber,
    ReverseDot1qCustomerVlanId = 245 => FieldDataType::UnsignedDataNumber,
    ReverseDot1qCustomerPriority = 246 => FieldDataType::UnsignedDataNumber,
    ReverseMetroEvcId = 247 => FieldDataType::String,
    ReverseMetroEvcType = 248 => FieldDataType::UnsignedDataNumber,
    ReversePseudoWireId = 249 => FieldDataType::UnsignedDataNumber,
    ReversePseudoWireType = 250 => FieldDataType::UnsignedDataNumber,
    ReversePseudoWireControlWord = 251 => FieldDataType::UnsignedDataNumber,
    ReverseIngressPhysicalInterface = 252 => FieldDataType::UnsignedDataNumber,
    ReverseEgressPhysicalInterface = 253 => FieldDataType::UnsignedDataNumber,
    ReversePostDot1qVlanId = 254 => FieldDataType::UnsignedDataNumber,
    ReversePostDot1qCustomerVlanId = 255 => FieldDataType::UnsignedDataNumber,
    ReverseEthernetType = 256 => FieldDataType::UnsignedDataNumber,
    ReversePostIpPrecedence = 257 => FieldDataType::UnsignedDataNumber,
    ReverseCollectionTimeMilliseconds = 258 => FieldDataType::UnsignedDataNumber,
    ReverseExportSctpStreamId = 259 => FieldDataType::UnsignedDataNumber,
    ReverseMaxExportSeconds = 260 => FieldDataType::UnsignedDataNumber,
    ReverseMaxFlowEndSeconds = 261 => FieldDataType::UnsignedDataNumber,
    ReverseMessageMD5Checksum = 262 => FieldDataType::String,
    ReverseMessageScope = 263 => FieldDataType::UnsignedDataNumber,
    ReverseMinExportSeconds = 264 => FieldDataType::UnsignedDataNumber,
    ReverseMinFlowStartSeconds = 265 => FieldDataType::UnsignedDataNumber,
    ReverseOpaqueOctets = 266 => FieldDataType::String,
    ReverseSessionScope = 267 => FieldDataType::UnsignedDataNumber,
    ReverseMaxFlowEndMicroseconds = 268 => FieldDataType::UnsignedDataNumber,
    ReverseMaxFlowEndMilliseconds = 269 => FieldDataType::UnsignedDataNumber,
    ReverseMaxFlowEndNanoseconds = 270 => FieldDataType::UnsignedDataNumber,
    ReverseMinFlowStartMicroseconds = 271 => FieldDataType::UnsignedDataNumber,
    ReverseMinFlowStartMilliseconds = 272 => FieldDataType::UnsignedDataNumber,
    ReverseMinFlowStartNanoseconds = 273 => FieldDataType::UnsignedDataNumber,
    ReverseCollectorCertificate = 274 => FieldDataType::String,
    ReverseExporterCertificate = 275 => FieldDataType::String,
    ReverseDataRecordsReliability = 276 => FieldDataType::UnsignedDataNumber,
    ReverseObservationPointType = 277 => FieldDataType::UnsignedDataNumber,
    ReverseNewConnectionDeltaCount = 278 => FieldDataType::UnsignedDataNumber,
    ReverseConnectionSumDurationSeconds = 279 => FieldDataType::UnsignedDataNumber,
    ReverseConnectionTransactionId = 280 => FieldDataType::UnsignedDataNumber,
    ReversePostNATSourceIPv6Address = 281 => FieldDataType::Ip6Addr,
    ReversePostNATDestinationIPv6Address = 282 => FieldDataType::Ip6Addr,
    ReverseNatPoolId = 283 => FieldDataType::UnsignedDataNumber,
    ReverseNatPoolName = 284 => FieldDataType::String,
    ReverseAnonymizationFlags = 285 => FieldDataType::UnsignedDataNumber,
    ReverseAnonymizationTechnique = 286 => FieldDataType::UnsignedDataNumber,
    ReverseInformationElementIndex = 287 => FieldDataType::UnsignedDataNumber,
    ReverseP2pTechnology = 288 => FieldDataType::String,
    ReverseTunnelTechnology = 289 => FieldDataType::String,
    ReverseEncryptedTechnology = 290 => FieldDataType::String,
    // 291, 292, 293 are :skip, so we omit them
    ReverseBgpValidityState = 294 => FieldDataType::UnsignedDataNumber,
    ReverseIPSecSPI = 295 => FieldDataType::UnsignedDataNumber,
    ReverseGreKey = 296 => FieldDataType::UnsignedDataNumber,
    ReverseNatType = 297 => FieldDataType::UnsignedDataNumber,
    ReverseInitiatorPackets = 298 => FieldDataType::UnsignedDataNumber,
    ReverseResponderPackets = 299 => FieldDataType::UnsignedDataNumber,
    ReverseObservationDomainName = 300 => FieldDataType::String,
    ReverseSelectionSequenceId = 301 => FieldDataType::UnsignedDataNumber,
    ReverseSelectorId = 302 => FieldDataType::UnsignedDataNumber,
    ReverseInformationElementId = 303 => FieldDataType::UnsignedDataNumber,
    ReverseSelectorAlgorithm = 304 => FieldDataType::UnsignedDataNumber,
    ReverseSamplingPacketInterval = 305 => FieldDataType::UnsignedDataNumber,
    ReverseSamplingPacketSpace = 306 => FieldDataType::UnsignedDataNumber,
    ReverseSamplingTimeInterval = 307 => FieldDataType::UnsignedDataNumber,
    ReverseSamplingTimeSpace = 308 => FieldDataType::UnsignedDataNumber,
    ReverseSamplingSize = 309 => FieldDataType::UnsignedDataNumber,
    ReverseSamplingPopulation = 310 => FieldDataType::UnsignedDataNumber,
    ReverseSamplingProbability = 311 => FieldDataType::Float64,
    ReverseDataLinkFrameSize = 312 => FieldDataType::UnsignedDataNumber,
    ReverseIpHeaderPacketSection = 313 => FieldDataType::String,
    ReverseIpPayloadPacketSection = 314 => FieldDataType::String,
    ReverseDataLinkFrameSection = 315 => FieldDataType::String,
    ReverseMplsLabelStackSection = 316 => FieldDataType::String,
    ReverseMplsPayloadPacketSection = 317 => FieldDataType::String,
    ReverseSelectorIdTotalPktsObserved = 318 => FieldDataType::UnsignedDataNumber,
    ReverseSelectorIdTotalPktsSelected = 319 => FieldDataType::UnsignedDataNumber,
    ReverseAbsoluteError = 320 => FieldDataType::Float64,
    ReverseRelativeError = 321 => FieldDataType::Float64,
    ReverseObservationTimeSeconds = 322 => FieldDataType::UnsignedDataNumber,
    ReverseObservationTimeMilliseconds = 323 => FieldDataType::UnsignedDataNumber,
    ReverseObservationTimeMicroseconds = 324 => FieldDataType::UnsignedDataNumber,
    ReverseObservationTimeNanoseconds = 325 => FieldDataType::UnsignedDataNumber,
    ReverseDigestHashValue = 326 => FieldDataType::UnsignedDataNumber,
    ReverseHashIPPayloadOffset = 327 => FieldDataType::UnsignedDataNumber,
    ReverseHashIPPayloadSize = 328 => FieldDataType::UnsignedDataNumber,
    ReverseHashOutputRangeMin = 329 => FieldDataType::UnsignedDataNumber,
    ReverseHashOutputRangeMax = 330 => FieldDataType::UnsignedDataNumber,
    ReverseHashSelectedRangeMin = 331 => FieldDataType::UnsignedDataNumber,
    ReverseHashSelectedRangeMax = 332 => FieldDataType::UnsignedDataNumber,
    ReverseHashDigestOutput = 333 => FieldDataType::UnsignedDataNumber,
    ReverseHashInitialiserValue = 334 => FieldDataType::UnsignedDataNumber,
    ReverseSelectorName = 335 => FieldDataType::String,
    ReverseUpperCILimit = 336 => FieldDataType::Float64,
    ReverseLowerCILimit = 337 => FieldDataType::Float64,
    ReverseConfidenceLevel = 338 => FieldDataType::Float64,
    ReverseInformationElementDataType = 339 => FieldDataType::UnsignedDataNumber,
    ReverseInformationElementDescription = 340 => FieldDataType::String,
    ReverseInformationElementName = 341 => FieldDataType::String,
    ReverseInformationElementRangeBegin = 342 => FieldDataType::UnsignedDataNumber,
    ReverseInformationElementRangeEnd = 343 => FieldDataType::UnsignedDataNumber,
    ReverseInformationElementSemantics = 344 => FieldDataType::UnsignedDataNumber,
    ReverseInformationElementUnits = 345 => FieldDataType::UnsignedDataNumber,
    ReversePrivateEnterpriseNumber = 346 => FieldDataType::UnsignedDataNumber,
    ReverseVirtualStationInterfaceId = 347 => FieldDataType::String,
    ReverseVirtualStationInterfaceName = 348 => FieldDataType::String,
    ReverseVirtualStationUUID = 349 => FieldDataType::String,
    ReverseVirtualStationName = 350 => FieldDataType::String,
    ReverseLayer2SegmentId = 351 => FieldDataType::UnsignedDataNumber,
    ReverseLayer2OctetDeltaCount = 352 => FieldDataType::UnsignedDataNumber,
    ReverseLayer2OctetTotalCount = 353 => FieldDataType::UnsignedDataNumber,
    ReverseIngressUnicastPacketTotalCount = 354 => FieldDataType::UnsignedDataNumber,
    ReverseIngressMulticastPacketTotalCount = 355 => FieldDataType::UnsignedDataNumber,
    ReverseIngressBroadcastPacketTotalCount = 356 => FieldDataType::UnsignedDataNumber,
    ReverseEgressUnicastPacketTotalCount = 357 => FieldDataType::UnsignedDataNumber,
    ReverseEgressBroadcastPacketTotalCount = 358 => FieldDataType::UnsignedDataNumber,
    ReverseMonitoringIntervalStartMilliSeconds = 359 => FieldDataType::UnsignedDataNumber,
    ReverseMonitoringIntervalEndMilliSeconds = 360 => FieldDataType::UnsignedDataNumber,
    ReversePortRangeStart = 361 => FieldDataType::UnsignedDataNumber,
    ReversePortRangeEnd = 362 => FieldDataType::UnsignedDataNumber,
    ReversePortRangeStepSize = 363 => FieldDataType::UnsignedDataNumber,
    ReversePortRangeNumPorts = 364 => FieldDataType::UnsignedDataNumber,
    ReverseStaMacAddress = 365 => FieldDataType::MacAddr,
    ReverseStaIPv4Address = 366 => FieldDataType::Ip4Addr,
    ReverseWtpMacAddress = 367 => FieldDataType::MacAddr,
    ReverseIngressInterfaceType = 368 => FieldDataType::UnsignedDataNumber,
    ReverseEgressInterfaceType = 369 => FieldDataType::UnsignedDataNumber,
    ReverseRtpSequenceNumber = 370 => FieldDataType::UnsignedDataNumber,
    ReverseUserName = 371 => FieldDataType::String,
    ReverseApplicationCategoryName = 372 => FieldDataType::String,
    ReverseApplicationSubCategoryName = 373 => FieldDataType::String,
    ReverseApplicationGroupName = 374 => FieldDataType::String,
    ReverseOriginalFlowsPresent = 375 => FieldDataType::UnsignedDataNumber,
    ReverseOriginalFlowsInitiated = 376 => FieldDataType::UnsignedDataNumber,
    ReverseOriginalFlowsCompleted = 377 => FieldDataType::UnsignedDataNumber,
    ReverseDistinctCountOfSourceIPAddress = 378 => FieldDataType::UnsignedDataNumber,
    ReverseDistinctCountOfDestinationIPAddress = 379 => FieldDataType::UnsignedDataNumber,
    ReverseDistinctCountOfSourceIPv4Address = 380 => FieldDataType::UnsignedDataNumber,
    ReverseDistinctCountOfDestinationIPv4Address = 381 => FieldDataType::UnsignedDataNumber,
    ReverseDistinctCountOfSourceIPv6Address = 382 => FieldDataType::UnsignedDataNumber,
    ReverseDistinctCountOfDestinationIPv6Address = 383 => FieldDataType::UnsignedDataNumber,
    ReverseValueDistributionMethod = 384 => FieldDataType::UnsignedDataNumber,
    ReverseRfc3550JitterMilliseconds = 385 => FieldDataType::UnsignedDataNumber,
    ReverseRfc3550JitterMicroseconds = 386 => FieldDataType::UnsignedDataNumber,
    ReverseRfc3550JitterNanoseconds = 387 => FieldDataType::UnsignedDataNumber,
    ReverseDot1qDEI = 388 => FieldDataType::UnsignedDataNumber,
    ReverseDot1qCustomerDEI = 389 => FieldDataType::UnsignedDataNumber,
    ReverseFlowSelectorAlgorithm = 390 => FieldDataType::UnsignedDataNumber,
    ReverseFlowSelectedOctetDeltaCount = 391 => FieldDataType::UnsignedDataNumber,
    ReverseFlowSelectedPacketDeltaCount = 392 => FieldDataType::UnsignedDataNumber,
    ReverseFlowSelectedFlowDeltaCount = 393 => FieldDataType::UnsignedDataNumber,
    ReverseSelectorIDTotalFlowsObserved = 394 => FieldDataType::UnsignedDataNumber,
    ReverseSelectorIDTotalFlowsSelected = 395 => FieldDataType::UnsignedDataNumber,
    ReverseSamplingFlowInterval = 396 => FieldDataType::UnsignedDataNumber,
    ReverseSamplingFlowSpacing = 397 => FieldDataType::UnsignedDataNumber,
    ReverseFlowSamplingTimeInterval = 398 => FieldDataType::UnsignedDataNumber,
    ReverseFlowSamplingTimeSpacing = 399 => FieldDataType::UnsignedDataNumber,
    ReverseHashFlowDomain = 400 => FieldDataType::UnsignedDataNumber,
    ReverseTransportOctetDeltaCount = 401 => FieldDataType::UnsignedDataNumber,
    ReverseTransportPacketDeltaCount = 402 => FieldDataType::UnsignedDataNumber,
    ReverseOriginalExporterIPv4Address = 403 => FieldDataType::Ip4Addr,
    ReverseOriginalExporterIPv6Address = 404 => FieldDataType::Ip6Addr,
    ReverseOriginalObservationDomainId = 405 => FieldDataType::UnsignedDataNumber,
    ReverseIntermediateProcessId = 406 => FieldDataType::UnsignedDataNumber,
    ReverseIgnoredDataRecordTotalCount = 407 => FieldDataType::UnsignedDataNumber,
    ReverseDataLinkFrameType = 408 => FieldDataType::UnsignedDataNumber,
    ReverseSectionOffset = 409 => FieldDataType::UnsignedDataNumber,
    ReverseSectionExportedOctets = 410 => FieldDataType::UnsignedDataNumber,
    ReverseDot1qServiceInstanceTag = 411 => FieldDataType::String,
    ReverseDot1qServiceInstanceId = 412 => FieldDataType::UnsignedDataNumber,
    ReverseDot1qServiceInstancePriority = 413 => FieldDataType::UnsignedDataNumber,
    ReverseDot1qCustomerSourceMacAddress = 414 => FieldDataType::MacAddr,
    ReverseDot1qCustomerDestinationMacAddress = 415 => FieldDataType::MacAddr,
    ReversePostLayer2OctetDeltaCount = 417 => FieldDataType::UnsignedDataNumber,
    ReversePostMCastLayer2OctetDeltaCount = 418 => FieldDataType::UnsignedDataNumber,
    ReversePostLayer2OctetTotalCount = 420 => FieldDataType::UnsignedDataNumber,
    ReversePostMCastLayer2OctetTotalCount = 421 => FieldDataType::UnsignedDataNumber,
    ReverseMinimumLayer2TotalLength = 422 => FieldDataType::UnsignedDataNumber,
    ReverseMaximumLayer2TotalLength = 423 => FieldDataType::UnsignedDataNumber,
    ReverseDroppedLayer2OctetDeltaCount = 424 => FieldDataType::UnsignedDataNumber,
    ReverseDroppedLayer2OctetTotalCount = 425 => FieldDataType::UnsignedDataNumber,
    ReverseIgnoredLayer2OctetTotalCount = 426 => FieldDataType::UnsignedDataNumber,
    ReverseNotSentLayer2OctetTotalCount = 427 => FieldDataType::UnsignedDataNumber,
    ReverseLayer2OctetDeltaSumOfSquares = 428 => FieldDataType::UnsignedDataNumber,
    ReverseLayer2OctetTotalSumOfSquares = 429 => FieldDataType::UnsignedDataNumber,
    ReverseLayer2FrameDeltaCount = 430 => FieldDataType::UnsignedDataNumber,
    ReverseLayer2FrameTotalCount = 431 => FieldDataType::UnsignedDataNumber,
    ReversePseudoWireDestinationIPv4Address = 432 => FieldDataType::Ip4Addr,
    ReverseIgnoredLayer2FrameTotalCount = 433 => FieldDataType::UnsignedDataNumber,
    }
}

ipfix_field_enum! {
#[repr(u16)]
#[derive(Debug, Hash, PartialEq, Eq, Clone, Ord, PartialOrd, Copy, Serialize)]
    pub enum IANAIPFixField {
Reserved = 0 => FieldDataType::Unknown,
OctetDeltaCount = 1 => FieldDataType::UnsignedDataNumber,
PacketDeltaCount = 2 => FieldDataType::UnsignedDataNumber,
DeltaFlowCount = 3 => FieldDataType::UnsignedDataNumber,
ProtocolIdentifier = 4 => FieldDataType::ProtocolType,
IpClassOfService = 5 => FieldDataType::UnsignedDataNumber,
TcpControlBits = 6 => FieldDataType::UnsignedDataNumber,
SourceTransportPort = 7 => FieldDataType::UnsignedDataNumber,
SourceIpv4address = 8 => FieldDataType::Ip4Addr,
SourceIpv4prefixLength = 9 => FieldDataType::UnsignedDataNumber,
IngressInterface = 10 => FieldDataType::UnsignedDataNumber,
DestinationTransportPort = 11 => FieldDataType::UnsignedDataNumber,
DestinationIpv4address = 12 => FieldDataType::Ip4Addr,
DestinationIpv4prefixLength = 13 => FieldDataType::UnsignedDataNumber,
EgressInterface = 14 => FieldDataType::UnsignedDataNumber,
IpNextHopIpv4address = 15 => FieldDataType::Ip4Addr,
BgpSourceAsNumber = 16 => FieldDataType::UnsignedDataNumber,
BgpDestinationAsNumber = 17 => FieldDataType::UnsignedDataNumber,
BgpNextHopIpv4address = 18 => FieldDataType::Ip4Addr,
PostMcastPacketDeltaCount = 19 => FieldDataType::UnsignedDataNumber,
PostMcastOctetDeltaCount = 20 => FieldDataType::UnsignedDataNumber,
FlowEndSysUpTime = 21 => FieldDataType::UnsignedDataNumber,
FlowStartSysUpTime = 22 => FieldDataType::UnsignedDataNumber,
PostOctetDeltaCount = 23 => FieldDataType::UnsignedDataNumber,
PostPacketDeltaCount = 24 => FieldDataType::UnsignedDataNumber,
MinimumIpTotalLength = 25 => FieldDataType::UnsignedDataNumber,
MaximumIpTotalLength = 26 => FieldDataType::UnsignedDataNumber,
SourceIpv6address = 27 => FieldDataType::Ip6Addr,
DestinationIpv6address = 28 => FieldDataType::Ip6Addr,
SourceIpv6prefixLength = 29 => FieldDataType::UnsignedDataNumber,
DestinationIpv6prefixLength = 30 => FieldDataType::UnsignedDataNumber,
FlowLabelIpv6 = 31 => FieldDataType::UnsignedDataNumber,
IcmpTypeCodeIpv4 = 32 => FieldDataType::UnsignedDataNumber,
IgmpType = 33 => FieldDataType::UnsignedDataNumber,
SamplingInterval = 34 => FieldDataType::UnsignedDataNumber,
SamplingAlgorithm = 35 => FieldDataType::UnsignedDataNumber,
FlowActiveTimeout = 36 => FieldDataType::UnsignedDataNumber,
FlowIdleTimeout = 37 => FieldDataType::UnsignedDataNumber,
EngineType = 38 => FieldDataType::UnsignedDataNumber,
EngineId = 39 => FieldDataType::UnsignedDataNumber,
ExportedOctetTotalCount = 40 => FieldDataType::UnsignedDataNumber,
ExportedMessageTotalCount = 41 => FieldDataType::UnsignedDataNumber,
ExportedFlowRecordTotalCount = 42 => FieldDataType::UnsignedDataNumber,
Ipv4routerSc = 43 => FieldDataType::Ip4Addr,
SourceIpv4prefix = 44 => FieldDataType::Ip4Addr,
DestinationIpv4prefix = 45 => FieldDataType::Ip4Addr,
MplsTopLabelType = 46 => FieldDataType::UnsignedDataNumber,
MplsTopLabelIpv4address = 47 => FieldDataType::Ip4Addr,
SamplerId = 48 => FieldDataType::UnsignedDataNumber,
SamplerMode = 49 => FieldDataType::UnsignedDataNumber,
SamplerRandomInterval = 50 => FieldDataType::UnsignedDataNumber,
ClassId = 51 => FieldDataType::UnsignedDataNumber,
MinimumTtl = 52 => FieldDataType::UnsignedDataNumber,
MaximumTtl = 53 => FieldDataType::UnsignedDataNumber,
FragmentIdentification = 54 => FieldDataType::UnsignedDataNumber,
PostIpClassOfService = 55 => FieldDataType::UnsignedDataNumber,
SourceMacaddress = 56 => FieldDataType::MacAddr,
PostDestinationMacaddress = 57 => FieldDataType::MacAddr,
VlanId = 58 => FieldDataType::UnsignedDataNumber,
PostVlanId = 59 => FieldDataType::UnsignedDataNumber,
IpVersion = 60 => FieldDataType::UnsignedDataNumber,
FlowDirection = 61 => FieldDataType::UnsignedDataNumber,
IpNextHopIpv6address = 62 => FieldDataType::Ip6Addr,
BgpNextHopIpv6address = 63 => FieldDataType::Ip6Addr,
Ipv6extensionHeaders = 64 => FieldDataType::UnsignedDataNumber,
AssignedforNetFlowv9compatibility65 = 65 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility66 = 66 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility67 = 67 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility68 = 68 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility69 = 69 => FieldDataType::Unknown,
MplsTopLabelStackSection = 70 => FieldDataType::String,
MplsLabelStackSection2 = 71 => FieldDataType::String,
MplsLabelStackSection3 = 72 => FieldDataType::String,
MplsLabelStackSection4 = 73 => FieldDataType::String,
MplsLabelStackSection5 = 74 => FieldDataType::String,
MplsLabelStackSection6 = 75 => FieldDataType::String,
MplsLabelStackSection7 = 76 => FieldDataType::String,
MplsLabelStackSection8 = 77 => FieldDataType::String,
MplsLabelStackSection9 = 78 => FieldDataType::String,
MplsLabelStackSection10 = 79 => FieldDataType::String,
DestinationMacaddress = 80 => FieldDataType::MacAddr,
PostSourceMacaddress = 81 => FieldDataType::MacAddr,
InterfaceName = 82 => FieldDataType::String,
InterfaceDescription = 83 => FieldDataType::String,
SamplerName = 84 => FieldDataType::String,
OctetTotalCount = 85 => FieldDataType::UnsignedDataNumber,
PacketTotalCount = 86 => FieldDataType::UnsignedDataNumber,
FlagsAndSamplerId = 87 => FieldDataType::UnsignedDataNumber,
FragmentOffset = 88 => FieldDataType::UnsignedDataNumber,
ForwardingStatus = 89 => FieldDataType::UnsignedDataNumber,
MplsVpnRouteDistinguisher = 90 => FieldDataType::String,
MplsTopLabelprefixLength = 91 => FieldDataType::UnsignedDataNumber,
SrcTrafficIndex = 92 => FieldDataType::UnsignedDataNumber,
DstTrafficIndex = 93 => FieldDataType::UnsignedDataNumber,
ApplicationDescription = 94 => FieldDataType::String,
ApplicationId = 95 => FieldDataType::ApplicationId,
ApplicationName = 96 => FieldDataType::String,
AssignedforNetFlowv9compatibility96 = 97 => FieldDataType::Unknown,
PostIpDiffServCodePoint = 98 => FieldDataType::UnsignedDataNumber,
MulticastReplicationFactor = 99 => FieldDataType::UnsignedDataNumber,
ClassName = 100 => FieldDataType::String,
ClassificationEngineId = 101 => FieldDataType::UnsignedDataNumber,
Layer2packetSectionOffset = 102 => FieldDataType::UnsignedDataNumber,
Layer2packetSectionSize = 103 => FieldDataType::UnsignedDataNumber,
Layer2packetSectionData = 104 => FieldDataType::String,
AssignedforNetFlowv9compatibility105 = 105 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility106 = 106 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility107 = 107 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility108 = 108 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility109 = 109 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility110 = 110 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility111 = 111 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility112 = 112 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility113 = 113 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility114 = 114 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility115 = 115 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility116 = 116 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility117 = 117 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility118 = 118 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility119 = 119 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility120 = 120 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility121 = 121 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility122 = 122 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility123 = 123 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility124 = 124 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility125 = 125 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility126 = 126 => FieldDataType::Unknown,
AssignedforNetFlowv9compatibility127 = 127 => FieldDataType::Unknown,
BgpNextAdjacentAsNumber = 128 => FieldDataType::UnsignedDataNumber,
BgpPrevAdjacentAsNumber = 129 => FieldDataType::UnsignedDataNumber,
ExporterIpv4address = 130 => FieldDataType::Ip4Addr,
ExporterIpv6address = 131 => FieldDataType::Ip6Addr,
DroppedOctetDeltaCount = 132 => FieldDataType::UnsignedDataNumber,
DroppedPacketDeltaCount = 133 => FieldDataType::UnsignedDataNumber,
DroppedOctetTotalCount = 134 => FieldDataType::UnsignedDataNumber,
DroppedPacketTotalCount = 135 => FieldDataType::UnsignedDataNumber,
FlowEndReason = 136 => FieldDataType::UnsignedDataNumber,
CommonPropertiesId = 137 => FieldDataType::UnsignedDataNumber,
ObservationPointId = 138 => FieldDataType::UnsignedDataNumber,
IcmpTypeCodeIpv6 = 139 => FieldDataType::UnsignedDataNumber,
MplsTopLabelIpv6address = 140 => FieldDataType::Ip6Addr,
LineCardId = 141 => FieldDataType::UnsignedDataNumber,
PortId = 142 => FieldDataType::UnsignedDataNumber,
MeteringProcessId = 143 => FieldDataType::UnsignedDataNumber,
ExportingProcessId = 144 => FieldDataType::UnsignedDataNumber,
TemplateId = 145 => FieldDataType::UnsignedDataNumber,
WlanChannelId = 146 => FieldDataType::UnsignedDataNumber,
WlanSsid = 147 => FieldDataType::String,
FlowId = 148 => FieldDataType::UnsignedDataNumber,
ObservationDomainId = 149 => FieldDataType::UnsignedDataNumber,
FlowStartSeconds = 150 => FieldDataType::DurationSeconds,
FlowEndSeconds = 151 => FieldDataType::DurationSeconds,
FlowStartMilliseconds = 152 => FieldDataType::DurationMillis,
FlowEndMilliseconds = 153 => FieldDataType::DurationMillis,
FlowStartMicroseconds = 154 => FieldDataType::DurationMicrosNTP,
FlowEndMicroseconds = 155 => FieldDataType::DurationMicrosNTP,
FlowStartNanoseconds = 156 => FieldDataType::DurationNanosNTP,
FlowEndNanoseconds = 157 => FieldDataType::DurationNanosNTP,
FlowStartDeltaMicroseconds = 158 => FieldDataType::UnsignedDataNumber,
FlowEndDeltaMicroseconds = 159 => FieldDataType::UnsignedDataNumber,
SystemInitTimeMilliseconds = 160 => FieldDataType::DurationMillis,
FlowDurationMilliseconds = 161 => FieldDataType::UnsignedDataNumber,
FlowDurationMicroseconds = 162 => FieldDataType::UnsignedDataNumber,
ObservedFlowTotalCount = 163 => FieldDataType::UnsignedDataNumber,
IgnoredPacketTotalCount = 164 => FieldDataType::UnsignedDataNumber,
IgnoredOctetTotalCount = 165 => FieldDataType::UnsignedDataNumber,
NotSentFlowTotalCount = 166 => FieldDataType::UnsignedDataNumber,
NotSentPacketTotalCount = 167 => FieldDataType::UnsignedDataNumber,
NotSentOctetTotalCount = 168 => FieldDataType::UnsignedDataNumber,
DestinationIpv6prefix = 169 => FieldDataType::Ip6Addr,
SourceIpv6prefix = 170 => FieldDataType::Ip6Addr,
PostOctetTotalCount = 171 => FieldDataType::UnsignedDataNumber,
PostPacketTotalCount = 172 => FieldDataType::UnsignedDataNumber,
FlowKeyIndicator = 173 => FieldDataType::UnsignedDataNumber,
PostMcastPacketTotalCount = 174 => FieldDataType::UnsignedDataNumber,
PostMcastOctetTotalCount = 175 => FieldDataType::UnsignedDataNumber,
IcmpTypeIpv4 = 176 => FieldDataType::UnsignedDataNumber,
IcmpCodeIpv4 = 177 => FieldDataType::UnsignedDataNumber,
IcmpTypeIpv6 = 178 => FieldDataType::UnsignedDataNumber,
IcmpCodeIpv6 = 179 => FieldDataType::UnsignedDataNumber,
UdpSourcePort = 180 => FieldDataType::UnsignedDataNumber,
UdpDestinationPort = 181 => FieldDataType::UnsignedDataNumber,
TcpSourcePort = 182 => FieldDataType::UnsignedDataNumber,
TcpDestinationPort = 183 => FieldDataType::UnsignedDataNumber,
TcpSequenceNumber = 184 => FieldDataType::UnsignedDataNumber,
TcpAcknowledgementNumber = 185 => FieldDataType::UnsignedDataNumber,
TcpWindowSize = 186 => FieldDataType::UnsignedDataNumber,
TcpUrgentPointer = 187 => FieldDataType::UnsignedDataNumber,
TcpHeaderLength = 188 => FieldDataType::UnsignedDataNumber,
IpHeaderLength = 189 => FieldDataType::UnsignedDataNumber,
TotalLengthIpv4 = 190 => FieldDataType::UnsignedDataNumber,
PayloadLengthIpv6 = 191 => FieldDataType::UnsignedDataNumber,
IpTtl = 192 => FieldDataType::UnsignedDataNumber,
NextHeaderIpv6 = 193 => FieldDataType::UnsignedDataNumber,
MplsPayloadLength = 194 => FieldDataType::UnsignedDataNumber,
IpDiffServCodePoint = 195 => FieldDataType::UnsignedDataNumber,
IpPrecedence = 196 => FieldDataType::UnsignedDataNumber,
FragmentFlags = 197 => FieldDataType::UnsignedDataNumber,
OctetDeltaSumOfSquares = 198 => FieldDataType::UnsignedDataNumber,
OctetTotalSumOfSquares = 199 => FieldDataType::UnsignedDataNumber,
MplsTopLabelTtl = 200 => FieldDataType::UnsignedDataNumber,
MplsLabelStackLength = 201 => FieldDataType::UnsignedDataNumber,
MplsLabelStackDepth = 202 => FieldDataType::UnsignedDataNumber,
MplsTopLabelExp = 203 => FieldDataType::UnsignedDataNumber,
IpPayloadLength = 204 => FieldDataType::UnsignedDataNumber,
UdpMessageLength = 205 => FieldDataType::UnsignedDataNumber,
IsMulticast = 206 => FieldDataType::UnsignedDataNumber,
Ipv4ihl = 207 => FieldDataType::UnsignedDataNumber,
Ipv4options = 208 => FieldDataType::UnsignedDataNumber,
TcpOptions = 209 => FieldDataType::UnsignedDataNumber,
PaddingOctets = 210 => FieldDataType::String,
CollectorIpv4address = 211 => FieldDataType::Ip4Addr,
CollectorIpv6address = 212 => FieldDataType::Ip6Addr,
ExportInterface = 213 => FieldDataType::UnsignedDataNumber,
ExportProtocolVersion = 214 => FieldDataType::UnsignedDataNumber,
ExportTransportProtocol = 215 => FieldDataType::UnsignedDataNumber,
CollectorTransportPort = 216 => FieldDataType::UnsignedDataNumber,
ExporterTransportPort = 217 => FieldDataType::UnsignedDataNumber,
TcpSynTotalCount = 218 => FieldDataType::UnsignedDataNumber,
TcpFinTotalCount = 219 => FieldDataType::UnsignedDataNumber,
TcpRstTotalCount = 220 => FieldDataType::UnsignedDataNumber,
TcpPshTotalCount = 221 => FieldDataType::UnsignedDataNumber,
TcpAckTotalCount = 222 => FieldDataType::UnsignedDataNumber,
TcpUrgTotalCount = 223 => FieldDataType::UnsignedDataNumber,
IpTotalLength = 224 => FieldDataType::UnsignedDataNumber,
PostNatsourceIpv4address = 225 => FieldDataType::Ip4Addr,
PostNatdestinationIpv4address = 226 => FieldDataType::Ip4Addr,
PostNaptsourceTransportPort = 227 => FieldDataType::UnsignedDataNumber,
PostNaptdestinationTransportPort = 228 => FieldDataType::UnsignedDataNumber,
NatOriginatingaddressRealm = 229 => FieldDataType::UnsignedDataNumber,
NatEvent = 230 => FieldDataType::UnsignedDataNumber,
InitiatorOctets = 231 => FieldDataType::UnsignedDataNumber,
ResponderOctets = 232 => FieldDataType::UnsignedDataNumber,
FirewallEvent = 233 => FieldDataType::UnsignedDataNumber,
IngressVrfid = 234 => FieldDataType::UnsignedDataNumber,
EgressVrfid = 235 => FieldDataType::UnsignedDataNumber,
VRFname = 236 => FieldDataType::String,
PostMplsTopLabelExp = 237 => FieldDataType::UnsignedDataNumber,
TcpWindowScale = 238 => FieldDataType::UnsignedDataNumber,
BiflowDirection = 239 => FieldDataType::UnsignedDataNumber,
EthernetHeaderLength = 240 => FieldDataType::UnsignedDataNumber,
EthernetPayloadLength = 241 => FieldDataType::UnsignedDataNumber,
EthernetTotalLength = 242 => FieldDataType::UnsignedDataNumber,
Dot1qVlanId = 243 => FieldDataType::UnsignedDataNumber,
Dot1qPriority = 244 => FieldDataType::UnsignedDataNumber,
Dot1qCustomerVlanId = 245 => FieldDataType::UnsignedDataNumber,
Dot1qCustomerPriority = 246 => FieldDataType::UnsignedDataNumber,
MetroEvcId = 247 => FieldDataType::String,
MetroEvcType = 248 => FieldDataType::UnsignedDataNumber,
PseudoWireId = 249 => FieldDataType::UnsignedDataNumber,
PseudoWireType = 250 => FieldDataType::UnsignedDataNumber,
PseudoWireControlWord = 251 => FieldDataType::UnsignedDataNumber,
IngressPhysicalInterface = 252 => FieldDataType::UnsignedDataNumber,
EgressPhysicalInterface = 253 => FieldDataType::UnsignedDataNumber,
PostDot1qVlanId = 254 => FieldDataType::UnsignedDataNumber,
PostDot1qCustomerVlanId = 255 => FieldDataType::UnsignedDataNumber,
EthernetType = 256 => FieldDataType::UnsignedDataNumber,
PostIpPrecedence = 257 => FieldDataType::UnsignedDataNumber,
CollectionTimeMilliseconds = 258 => FieldDataType::DurationMillis,
ExportSctpStreamId = 259 => FieldDataType::UnsignedDataNumber,
MaxExportSeconds = 260 => FieldDataType::DurationSeconds,
MaxFlowEndSeconds = 261 => FieldDataType::DurationSeconds,
MessageMd5checksum = 262 => FieldDataType::String,
MessageScope = 263 => FieldDataType::UnsignedDataNumber,
MinExportSeconds = 264 => FieldDataType::DurationSeconds,
MinFlowStartSeconds = 265 => FieldDataType::DurationSeconds,
OpaqueOctets = 266 => FieldDataType::String,
SessionScope = 267 => FieldDataType::UnsignedDataNumber,
MaxFlowEndMicroseconds = 268 => FieldDataType::DurationMicrosNTP,
MaxFlowEndMilliseconds = 269 => FieldDataType::DurationMillis,
MaxFlowEndNanoseconds = 270 => FieldDataType::DurationNanosNTP,
MinFlowStartMicroseconds = 271 => FieldDataType::DurationMicrosNTP,
MinFlowStartMilliseconds = 272 => FieldDataType::DurationMillis,
MinFlowStartNanoseconds = 273 => FieldDataType::DurationNanosNTP,
CollectorCertificate = 274 => FieldDataType::String,
ExporterCertificate = 275 => FieldDataType::String,
DataRecordsReliability = 276 => FieldDataType::UnsignedDataNumber,
ObservationPointType = 277 => FieldDataType::UnsignedDataNumber,
NewConnectionDeltaCount = 278 => FieldDataType::UnsignedDataNumber,
ConnectionSumDurationSeconds = 279 => FieldDataType::UnsignedDataNumber,
ConnectionTransactionId = 280 => FieldDataType::UnsignedDataNumber,
PostNatsourceIpv6address = 281 => FieldDataType::Ip6Addr,
PostNatdestinationIpv6address = 282 => FieldDataType::Ip6Addr,
NatPoolId = 283 => FieldDataType::UnsignedDataNumber,
NatPoolName = 284 => FieldDataType::String,
AnonymizationFlags = 285 => FieldDataType::UnsignedDataNumber,
AnonymizationTechnique = 286 => FieldDataType::UnsignedDataNumber,
InformationElementIndex = 287 => FieldDataType::UnsignedDataNumber,
P2pTechnology = 288 => FieldDataType::String,
TunnelTechnology = 289 => FieldDataType::String,
EncryptedTechnology = 290 => FieldDataType::String,
BasicList = 291 => FieldDataType::Unknown,
SubTemplateList = 292 => FieldDataType::Unknown,
SubTemplateMultiList = 293 => FieldDataType::Unknown,
BgpValidityState = 294 => FieldDataType::UnsignedDataNumber,
IpSecSPI = 295 => FieldDataType::UnsignedDataNumber,
GreKey = 296 => FieldDataType::UnsignedDataNumber,
NatType = 297 => FieldDataType::UnsignedDataNumber,
InitiatorPackets = 298 => FieldDataType::UnsignedDataNumber,
ResponderPackets = 299 => FieldDataType::UnsignedDataNumber,
ObservationDomainName = 300 => FieldDataType::String,
SelectionSequenceId = 301 => FieldDataType::UnsignedDataNumber,
SelectorId = 302 => FieldDataType::UnsignedDataNumber,
InformationElementId = 303 => FieldDataType::UnsignedDataNumber,
SelectorAlgorithm = 304 => FieldDataType::UnsignedDataNumber,
SamplingPacketInterval = 305 => FieldDataType::UnsignedDataNumber,
SamplingPacketSpace = 306 => FieldDataType::UnsignedDataNumber,
SamplingTimeInterval = 307 => FieldDataType::UnsignedDataNumber,
SamplingTimeSpace = 308 => FieldDataType::UnsignedDataNumber,
SamplingSize = 309 => FieldDataType::UnsignedDataNumber,
SamplingPopulation = 310 => FieldDataType::UnsignedDataNumber,
SamplingProbability = 311 => FieldDataType::Float64,
DataLinkFrameSize = 312 => FieldDataType::UnsignedDataNumber,
IpHeaderPacketSection = 313 => FieldDataType::String,
IpPayloadPacketSection = 314 => FieldDataType::String,
DataLinkFrameSection = 315 => FieldDataType::String,
MplsLabelStackSection = 316 => FieldDataType::String,
MplsPayloadPacketSection = 317 => FieldDataType::String,
SelectorIdTotalPktsObserved = 318 => FieldDataType::UnsignedDataNumber,
SelectorIdTotalPktsSelected = 319 => FieldDataType::UnsignedDataNumber,
AbsoluteError = 320 => FieldDataType::Float64,
RelativeError = 321 => FieldDataType::Float64,
ObservationTimeSeconds = 322 => FieldDataType::DurationSeconds,
ObservationTimeMilliseconds = 323 => FieldDataType::DurationMillis,
ObservationTimeMicroseconds = 324 => FieldDataType::DurationMicrosNTP,
ObservationTimeNanoseconds = 325 => FieldDataType::DurationNanosNTP,
DigestHashValue = 326 => FieldDataType::UnsignedDataNumber,
HashIppayloadOffset = 327 => FieldDataType::UnsignedDataNumber,
HashIppayloadSize = 328 => FieldDataType::UnsignedDataNumber,
HashOutputRangeMin = 329 => FieldDataType::UnsignedDataNumber,
HashOutputRangeMax = 330 => FieldDataType::UnsignedDataNumber,
HashSelectedRangeMin = 331 => FieldDataType::UnsignedDataNumber,
HashSelectedRangeMax = 332 => FieldDataType::UnsignedDataNumber,
HashDigestOutput = 333 => FieldDataType::UnsignedDataNumber,
HashInitialiserValue = 334 => FieldDataType::UnsignedDataNumber,
SelectorName = 335 => FieldDataType::String,
UpperCilimit = 336 => FieldDataType::Float64,
LowerCilimit = 337 => FieldDataType::Float64,
ConfidenceLevel = 338 => FieldDataType::Float64,
InformationElementDataType = 339 => FieldDataType::UnsignedDataNumber,
InformationElementDescription = 340 => FieldDataType::String,
InformationElementName = 341 => FieldDataType::String,
InformationElementRangeBegin = 342 => FieldDataType::UnsignedDataNumber,
InformationElementRangeEnd = 343 => FieldDataType::UnsignedDataNumber,
InformationElementSemantics = 344 => FieldDataType::UnsignedDataNumber,
InformationElementUnits = 345 => FieldDataType::UnsignedDataNumber,
PrivateEnterpriseNumber = 346 => FieldDataType::UnsignedDataNumber,
VirtualStationInterfaceId = 347 => FieldDataType::String,
VirtualStationInterfaceName = 348 => FieldDataType::String,
VirtualStationUuid = 349 => FieldDataType::String,
VirtualStationName = 350 => FieldDataType::String,
Layer2segmentId = 351 => FieldDataType::UnsignedDataNumber,
Layer2octetDeltaCount = 352 => FieldDataType::UnsignedDataNumber,
Layer2octetTotalCount = 353 => FieldDataType::UnsignedDataNumber,
IngressUnicastPacketTotalCount = 354 => FieldDataType::UnsignedDataNumber,
IngressMulticastPacketTotalCount = 355 => FieldDataType::UnsignedDataNumber,
IngressBroadcastPacketTotalCount = 356 => FieldDataType::UnsignedDataNumber,
EgressUnicastPacketTotalCount = 357 => FieldDataType::UnsignedDataNumber,
EgressBroadcastPacketTotalCount = 358 => FieldDataType::UnsignedDataNumber,
MonitoringIntervalStartMilliSeconds = 359 => FieldDataType::DurationMillis,
MonitoringIntervalEndMilliSeconds = 360 => FieldDataType::DurationMillis,
PortRangeStart = 361 => FieldDataType::UnsignedDataNumber,
PortRangeEnd = 362 => FieldDataType::UnsignedDataNumber,
PortRangeStepSize = 363 => FieldDataType::UnsignedDataNumber,
PortRangeNumPorts = 364 => FieldDataType::UnsignedDataNumber,
StaMacaddress = 365 => FieldDataType::MacAddr,
StaIpv4address = 366 => FieldDataType::Ip4Addr,
WtpMacaddress = 367 => FieldDataType::MacAddr,
IngressInterfaceType = 368 => FieldDataType::UnsignedDataNumber,
EgressInterfaceType = 369 => FieldDataType::UnsignedDataNumber,
RtpSequenceNumber = 370 => FieldDataType::UnsignedDataNumber,
UserName = 371 => FieldDataType::String,
ApplicationCategoryName = 372 => FieldDataType::String,
ApplicationSubCategoryName = 373 => FieldDataType::String,
ApplicationGroupName = 374 => FieldDataType::String,
OriginalFlowsPresent = 375 => FieldDataType::UnsignedDataNumber,
OriginalFlowsInitiated = 376 => FieldDataType::UnsignedDataNumber,
OriginalFlowsCompleted = 377 => FieldDataType::UnsignedDataNumber,
DistinctCountOfSourceIpaddress = 378 => FieldDataType::UnsignedDataNumber,
DistinctCountOfDestinationIpaddress = 379 => FieldDataType::UnsignedDataNumber,
DistinctCountOfSourceIpv4address = 380 => FieldDataType::UnsignedDataNumber,
DistinctCountOfDestinationIpv4address = 381 => FieldDataType::UnsignedDataNumber,
DistinctCountOfSourceIpv6address = 382 => FieldDataType::UnsignedDataNumber,
DistinctCountOfDestinationIpv6address = 383 => FieldDataType::UnsignedDataNumber,
ValueDistributionMethod = 384 => FieldDataType::UnsignedDataNumber,
Rfc3550jitterMilliseconds = 385 => FieldDataType::UnsignedDataNumber,
Rfc3550jitterMicroseconds = 386 => FieldDataType::UnsignedDataNumber,
Rfc3550jitterNanoseconds = 387 => FieldDataType::UnsignedDataNumber,
Dot1qDei = 388 => FieldDataType::UnsignedDataNumber,
Dot1qCustomerDei = 389 => FieldDataType::UnsignedDataNumber,
FlowSelectorAlgorithm = 390 => FieldDataType::UnsignedDataNumber,
FlowSelectedOctetDeltaCount = 391 => FieldDataType::UnsignedDataNumber,
FlowSelectedPacketDeltaCount = 392 => FieldDataType::UnsignedDataNumber,
FlowSelectedFlowDeltaCount = 393 => FieldDataType::UnsignedDataNumber,
SelectorIdtotalFlowsObserved = 394 => FieldDataType::UnsignedDataNumber,
SelectorIdtotalFlowsSelected = 395 => FieldDataType::UnsignedDataNumber,
SamplingFlowInterval = 396 => FieldDataType::UnsignedDataNumber,
SamplingFlowSpacing = 397 => FieldDataType::UnsignedDataNumber,
FlowSamplingTimeInterval = 398 => FieldDataType::UnsignedDataNumber,
FlowSamplingTimeSpacing = 399 => FieldDataType::UnsignedDataNumber,
HashFlowDomain = 400 => FieldDataType::UnsignedDataNumber,
TransportOctetDeltaCount = 401 => FieldDataType::UnsignedDataNumber,
TransportPacketDeltaCount = 402 => FieldDataType::UnsignedDataNumber,
OriginalExporterIpv4address = 403 => FieldDataType::Ip4Addr,
OriginalExporterIpv6address = 404 => FieldDataType::Ip6Addr,
OriginalObservationDomainId = 405 => FieldDataType::UnsignedDataNumber,
IntermediateProcessId = 406 => FieldDataType::UnsignedDataNumber,
IgnoredDataRecordTotalCount = 407 => FieldDataType::UnsignedDataNumber,
DataLinkFrameType = 408 => FieldDataType::UnsignedDataNumber,
SectionOffset = 409 => FieldDataType::UnsignedDataNumber,
SectionExportedOctets = 410 => FieldDataType::UnsignedDataNumber,
Dot1qServiceInstanceTag = 411 => FieldDataType::String,
Dot1qServiceInstanceId = 412 => FieldDataType::UnsignedDataNumber,
Dot1qServiceInstancePriority = 413 => FieldDataType::UnsignedDataNumber,
Dot1qCustomerSourceMacaddress = 414 => FieldDataType::String,
Dot1qCustomerDestinationMacaddress = 415 => FieldDataType::MacAddr,
PostLayer2octetDeltaCount = 417 => FieldDataType::UnsignedDataNumber,
PostMcastLayer2octetDeltaCount = 418 => FieldDataType::UnsignedDataNumber,
PostLayer2octetTotalCount = 420 => FieldDataType::UnsignedDataNumber,
PostMcastLayer2octetTotalCount = 421 => FieldDataType::UnsignedDataNumber,
MinimumLayer2totalLength = 422 => FieldDataType::UnsignedDataNumber,
MaximumLayer2totalLength = 423 => FieldDataType::UnsignedDataNumber,
DroppedLayer2octetDeltaCount = 424 => FieldDataType::UnsignedDataNumber,
DroppedLayer2octetTotalCount = 425 => FieldDataType::UnsignedDataNumber,
IgnoredLayer2octetTotalCount = 426 => FieldDataType::UnsignedDataNumber,
NotSentLayer2octetTotalCount = 427 => FieldDataType::UnsignedDataNumber,
Layer2octetDeltaSumOfSquares = 428 => FieldDataType::UnsignedDataNumber,
Layer2octetTotalSumOfSquares = 429 => FieldDataType::UnsignedDataNumber,
Layer2frameDeltaCount = 430 => FieldDataType::UnsignedDataNumber,
Layer2frameTotalCount = 431 => FieldDataType::UnsignedDataNumber,
PseudoWireDestinationIpv4address = 432 => FieldDataType::Ip4Addr,
IgnoredLayer2frameTotalCount = 433 => FieldDataType::UnsignedDataNumber,
MibObjectValueInteger = 434 => FieldDataType::SignedDataNumber,
MibObjectValueOctetString = 435 => FieldDataType::String,
MibObjectValueOid = 436 => FieldDataType::String,
MibObjectValueBits = 437 => FieldDataType::String,
MibObjectValueIpaddress = 438 => FieldDataType::Ip4Addr,
MibObjectValueCounter = 439 => FieldDataType::UnsignedDataNumber,
MibObjectValueGauge = 440 => FieldDataType::UnsignedDataNumber,
MibObjectValueTimeTicks = 441 => FieldDataType::UnsignedDataNumber,
MibObjectValueUnsigned = 442 => FieldDataType::UnsignedDataNumber,
MibObjectValueTable = 443 => FieldDataType::String,
MibObjectValueRow = 444 => FieldDataType::String,
MibObjectIdentifier = 445 => FieldDataType::String,
MibSubIdentifier = 446 => FieldDataType::UnsignedDataNumber,
MibIndexIndicator = 447 => FieldDataType::UnsignedDataNumber,
MibCaptureTimeSemantics = 448 => FieldDataType::UnsignedDataNumber,
MibContextEngineId = 449 => FieldDataType::String,
MibContextName = 450 => FieldDataType::String,
MibObjectName = 451 => FieldDataType::String,
MibObjectDescription = 452 => FieldDataType::String,
MibObjectSyntax = 453 => FieldDataType::String,
MibModuleName = 454 => FieldDataType::String,
MobileImsi = 455 => FieldDataType::String,
MobileMsisdn = 456 => FieldDataType::String,
HttpStatusCode = 457 => FieldDataType::UnsignedDataNumber,
SourceTransportPortsLimit = 458 => FieldDataType::UnsignedDataNumber,
HttpRequestMethod = 459 => FieldDataType::String,
HttpRequestHost = 460 => FieldDataType::String,
HttpRequestTarget = 461 => FieldDataType::String,
HttpMessageVersion = 462 => FieldDataType::String,
NatInstanceId = 463 => FieldDataType::UnsignedDataNumber,
InternaladdressRealm = 464 => FieldDataType::String,
ExternaladdressRealm = 465 => FieldDataType::String,
NatQuotaExceededEvent = 466 => FieldDataType::UnsignedDataNumber,
NatThresholdEvent = 467 => FieldDataType::UnsignedDataNumber,
HttpUserAgent = 468 => FieldDataType::String,
HttpContentType = 469 => FieldDataType::String,
HttpReasonPhrase = 470 => FieldDataType::String,
MaxSessionEntries = 471 => FieldDataType::UnsignedDataNumber,
MaxBibentries = 472 => FieldDataType::UnsignedDataNumber,
MaxEntriesPerUser = 473 => FieldDataType::UnsignedDataNumber,
MaxSubscribers = 474 => FieldDataType::UnsignedDataNumber,
MaxFragmentsPendingReassembly = 475 => FieldDataType::UnsignedDataNumber,
AddressPoolHighThreshold = 476 => FieldDataType::UnsignedDataNumber,
AddressPoolLowThreshold = 477 => FieldDataType::UnsignedDataNumber,
AddressPortMappingHighThreshold = 478 => FieldDataType::UnsignedDataNumber,
AddressPortMappingLowThreshold = 479 => FieldDataType::UnsignedDataNumber,
AddressPortMappingPerUserHighThreshold = 480 => FieldDataType::UnsignedDataNumber,
GlobaladdressMappingHighThreshold = 481 => FieldDataType::UnsignedDataNumber,
VpnIdentifier = 482 => FieldDataType::String,
BgpCommunity = 483 => FieldDataType::UnsignedDataNumber,
BgpSourceCommunityList = 484 => FieldDataType::String,
BgpDestinationCommunityList = 485 => FieldDataType::String,
BgpExtendedCommunity = 486 => FieldDataType::String,
BgpSourceExtendedCommunityList = 487 => FieldDataType::String,
BgpDestinationExtendedCommunityList = 488 => FieldDataType::String,
BgpLargeCommunity = 489 => FieldDataType::String,
BgpSourceLargeCommunityList = 490 => FieldDataType::String,
BgpDestinationLargeCommunityList = 491 => FieldDataType::String,
SrhFlagsIpv6 = 492 => FieldDataType::UnsignedDataNumber,
SrhTagIpv6 = 493 => FieldDataType::UnsignedDataNumber,
SrhSegmentIpv6 = 494 => FieldDataType::Ip6Addr,
SrhActiveSegmentIpv6 = 495 => FieldDataType::Ip6Addr,
SrhSegmentIpv6basicList = 496 => FieldDataType::String,
SrhSegmentIpv6listSection = 497 => FieldDataType::String,
SrhSegmentsIpv6left = 498 => FieldDataType::UnsignedDataNumber,
SrhIpv6section = 499 => FieldDataType::String,
SrhIpv6activeSegmentType = 500 => FieldDataType::UnsignedDataNumber,
SrhSegmentIpv6locatorLength = 501 => FieldDataType::UnsignedDataNumber,
SrhSegmentIpv6endpointBehavior = 502 => FieldDataType::UnsignedDataNumber,
    }
}

#[cfg(test)]
mod ipfix_lookup_tests {

    use crate::variable_versions::data_number::FieldDataType;

    use super::IANAIPFixField;

    use insta::assert_yaml_snapshot;

    #[test]
    fn it_tests_field_lookup() {
        let mut lookup = vec![];

        for i in 0..=502 {
            lookup.push(IANAIPFixField::from(i));
        }

        assert_yaml_snapshot!(lookup);
    }

    #[test]
    fn it_tests_field_data_type_lookup() {
        let mut lookup: Vec<FieldDataType> = vec![];

        for i in 0..=502 {
            lookup.push(IANAIPFixField::from(i).into());
        }

        assert_yaml_snapshot!(lookup);
    }
}
