//! See: <https://www.ibm.com/docs/en/npi/1.3.0?topic=versions-v9-field-type-definitions>

use super::field_value::*;

use nom_derive::*;
use serde::Serialize;

#[repr(u16)]
#[derive(Default, Debug, PartialEq, Eq, Clone, Copy, Serialize, Nom)]
pub enum ScopeFieldType {
    System = 1,
    Interface = 2,
    LineCard = 3,
    NetflowCache = 4,
    Template = 5,
    #[default]
    Unknown,
}

impl From<u16> for ScopeFieldType {
    fn from(item: u16) -> Self {
        match item {
            1 => ScopeFieldType::System,
            2 => ScopeFieldType::Interface,
            3 => ScopeFieldType::LineCard,
            4 => ScopeFieldType::NetflowCache,
            5 => ScopeFieldType::Template,
            _ => ScopeFieldType::Unknown,
        }
    }
}

#[repr(u16)]
#[derive(Debug, Hash, PartialEq, Eq, Clone, Ord, PartialOrd, Copy, Serialize, Nom)]
pub enum V9Field {
    InBytes = 1,
    InPkts = 2,
    Flows = 3,
    Protocol = 4,
    SrcTos = 5,
    TcpFlags = 6,
    L4SrcPort = 7,
    Ipv4SrcAddr = 8,
    SrcMask = 9,
    InputSnmp = 10,
    L4DstPort = 11,
    Ipv4DstAddr = 12,
    DstMask = 13,
    OutputSnmp = 14,
    Ipv4NextHop = 15,
    SrcAs = 16,
    DstAs = 17,
    BgpIpv4NextHop = 18,
    MulDstPkts = 19,
    MulDstBytes = 20,
    LastSwitched = 21,
    FirstSwitched = 22,
    OutBytes = 23,
    OutPkts = 24,
    MinPktLngth = 25,
    MaxPktLngth = 26,
    Ipv6SrcAddr = 27,
    Ipv6DstAddr = 28,
    Ipv6SrcMask = 29,
    Ipv6DstMask = 30,
    Ipv6FlowLabel = 31,
    IcmpType = 32,
    MulIgmpType = 33,
    SamplingInterval = 34,
    SamplingAlgorithm = 35,
    FlowActiveTimeout = 36,
    FlowInactiveTimeout = 37,
    EngineType = 38,
    EngineId = 39,
    TotalBytesExp = 40,
    TotalPktsExp = 41,
    TotalFlowsExp = 42,
    Ipv4SrcPrefix = 44,
    Ipv4DstPrefix = 45,
    MplsTopLabelType = 46,
    MplsTopLabelIpAddr = 47,
    FlowSamplerId = 48,
    FlowSamplerMode = 49,
    FlowSamplerRandomInterval = 50,
    MinTtl = 52,
    MaxTtl = 53,
    Ipv4Ident = 54,
    DstTos = 55,
    InSrcMac = 56,
    OutDstMac = 57,
    SrcVlan = 58,
    DstVlan = 59,
    IpProtocolVersion = 60,
    Direction = 61,
    Ipv6NextHop = 62,
    BgpIpv6NextHop = 63,
    Ipv6OptionHeaders = 64,
    MplsLabel1 = 70,
    MplsLabel2 = 71,
    MplsLabel3 = 72,
    MplsLabel4 = 73,
    MplsLabel5 = 74,
    MplsLabel6 = 75,
    MplsLabel7 = 76,
    MplsLabel8 = 77,
    MplsLabel9 = 78,
    MplsLabel10 = 79,
    InDstMac = 80,
    OutSrcMac = 81,
    IfName = 82,
    IfDesc = 83,
    SamplerName = 84,
    InPermanentBytes = 85,
    InPermanentPkts = 86,
    FragmentOffset = 88,
    ForwardingStatus = 89,
    MplsPalRd = 90,
    MplsPrefixLen = 91,
    SrcTrafficIndex = 92,
    DstTrafficIndex = 93,
    ApplicationDescription = 94,
    ApplicationTag = 95,
    ApplicationName = 96,
    PostipDiffServCodePoint = 98,
    Replicationfactor = 99,
    Deprecated = 100,
    Layer2packetSectionOffset = 102,
    Layer2packetSectionSize = 103,
    Layer2packetSectionData = 104,
    BgpNextAdjacentAsNumber = 128,
    BgpPrevAdjacentAsNumber = 129,
    ExporterIpv4Address = 130,
    ExporterIpv6Address = 131,
    DroppedOctetDeltaCount = 132,
    DroppedPacketDeltaCount = 133,
    DroppedOctetTotalCount = 134,
    DroppedPacketTotalCount = 135,
    FlowEndReason = 136,
    CommonPropertiesId = 137,
    ObservationPointId = 138,
    IcmpTypeCodeIpv6 = 139,
    MplsTopLabelIpv6Address = 140,
    LineCardId = 141,
    PortId = 142,
    MeteringProcessId = 143,
    ExportingProcessId = 144,
    TemplateId = 145,
    WlanChannelId = 146,
    WlanSsid = 147,
    FlowId = 148,
    ObservationDomainId = 149,
    FlowStartSeconds = 150,
    FlowEndSeconds = 151,
    FlowStartMilliseconds = 152,
    FlowEndMilliseconds = 153,
    FlowStartMicroseconds = 154,
    FlowEndMicroseconds = 155,
    FlowStartNanoseconds = 156,
    FlowEndNanoseconds = 157,
    FlowStartDeltaMicroseconds = 158,
    FlowEndDeltaMicroseconds = 159,
    SystemInitTimeMilliseconds = 160,
    FlowDurationMilliseconds = 161,
    FlowDurationMicroseconds = 162,
    ObservedFlowTotalCount = 163,
    IgnoredPacketTotalCount = 164,
    IgnoredOctetTotalCount = 165,
    NotSentFlowTotalCount = 166,
    NotSentPacketTotalCount = 167,
    NotSentOctetTotalCount = 168,
    DestinationIpv6Prefix = 169,
    SourceIpv6Prefix = 170,
    PostOctetTotalCount = 171,
    PostPacketTotalCount = 172,
    FlowKeyIndicator = 173,
    PostMcastPacketTotalCount = 174,
    PostMcastOctetTotalCount = 175,
    IcmpTypeValue = 176,
    IcmpCodeValue = 177,
    IcmpIpv6TypeValue = 178,
    IcmpIpv6CodeValue = 179,
    PostNATSourceIPv4Address = 225,
    PostNATDestinationIPv4Address = 226,
    PostNATTSourceTransportPort = 227,
    PostNATTDestinationTransportPort = 228,
    NatEvent = 230,
    PostNATSourceIpv6Address = 281,
    PostNATDestinationIpv6Address = 282,
    ObservationTimeMilliseconds = 323,
    Vendor,
    Unknown,
}

impl From<V9Field> for FieldDataType {
    fn from(d: V9Field) -> FieldDataType {
        match d {
            V9Field::InBytes => FieldDataType::UnsignedDataNumber,
            V9Field::InPkts => FieldDataType::UnsignedDataNumber,
            V9Field::Flows => FieldDataType::UnsignedDataNumber,
            V9Field::Protocol => FieldDataType::ProtocolType,
            V9Field::SrcTos => FieldDataType::UnsignedDataNumber,
            V9Field::TcpFlags => FieldDataType::TcpControlBits,
            V9Field::L4SrcPort => FieldDataType::UnsignedDataNumber,
            V9Field::Ipv4SrcAddr => FieldDataType::Ip4Addr,
            V9Field::SrcMask => FieldDataType::UnsignedDataNumber,
            V9Field::InputSnmp => FieldDataType::UnsignedDataNumber,
            V9Field::L4DstPort => FieldDataType::UnsignedDataNumber,
            V9Field::Ipv4DstAddr => FieldDataType::Ip4Addr,
            V9Field::DstMask => FieldDataType::UnsignedDataNumber,
            V9Field::OutputSnmp => FieldDataType::UnsignedDataNumber,
            V9Field::Ipv4NextHop => FieldDataType::Ip4Addr,
            V9Field::SrcAs => FieldDataType::UnsignedDataNumber,
            V9Field::DstAs => FieldDataType::UnsignedDataNumber,
            V9Field::BgpIpv4NextHop => FieldDataType::Ip4Addr,
            V9Field::MulDstPkts => FieldDataType::UnsignedDataNumber,
            V9Field::MulDstBytes => FieldDataType::UnsignedDataNumber,
            V9Field::LastSwitched => FieldDataType::DurationMillis,
            V9Field::FirstSwitched => FieldDataType::DurationMillis,
            V9Field::OutBytes => FieldDataType::UnsignedDataNumber,
            V9Field::OutPkts => FieldDataType::UnsignedDataNumber,
            V9Field::MinPktLngth => FieldDataType::UnsignedDataNumber,
            V9Field::MaxPktLngth => FieldDataType::UnsignedDataNumber,
            V9Field::Ipv6SrcAddr => FieldDataType::Ip6Addr,
            V9Field::Ipv6DstAddr => FieldDataType::Ip6Addr,
            V9Field::Ipv6SrcMask => FieldDataType::UnsignedDataNumber,
            V9Field::Ipv6DstMask => FieldDataType::UnsignedDataNumber,
            V9Field::Ipv6FlowLabel => FieldDataType::UnsignedDataNumber,
            V9Field::IcmpType => FieldDataType::UnsignedDataNumber,
            V9Field::MulIgmpType => FieldDataType::UnsignedDataNumber,
            V9Field::SamplingInterval => FieldDataType::UnsignedDataNumber,
            V9Field::SamplingAlgorithm => FieldDataType::UnsignedDataNumber,
            V9Field::FlowActiveTimeout => FieldDataType::UnsignedDataNumber,
            V9Field::FlowInactiveTimeout => FieldDataType::UnsignedDataNumber,
            V9Field::EngineType => FieldDataType::UnsignedDataNumber,
            V9Field::EngineId => FieldDataType::UnsignedDataNumber,
            V9Field::TotalBytesExp => FieldDataType::UnsignedDataNumber,
            V9Field::TotalPktsExp => FieldDataType::UnsignedDataNumber,
            V9Field::TotalFlowsExp => FieldDataType::UnsignedDataNumber,
            V9Field::Ipv4SrcPrefix => FieldDataType::Ip4Addr,
            V9Field::Ipv4DstPrefix => FieldDataType::Ip4Addr,
            V9Field::MplsTopLabelType => FieldDataType::MplsTopLabelType,
            V9Field::MplsTopLabelIpAddr => FieldDataType::Ip4Addr,
            V9Field::FlowSamplerId => FieldDataType::UnsignedDataNumber,
            V9Field::FlowSamplerMode => FieldDataType::UnsignedDataNumber,
            V9Field::FlowSamplerRandomInterval => FieldDataType::UnsignedDataNumber,
            V9Field::MinTtl => FieldDataType::UnsignedDataNumber,
            V9Field::MaxTtl => FieldDataType::UnsignedDataNumber,
            V9Field::Ipv4Ident => FieldDataType::UnsignedDataNumber,
            V9Field::DstTos => FieldDataType::UnsignedDataNumber,
            V9Field::InSrcMac => FieldDataType::MacAddr,
            V9Field::OutDstMac => FieldDataType::MacAddr,
            V9Field::SrcVlan => FieldDataType::UnsignedDataNumber,
            V9Field::DstVlan => FieldDataType::UnsignedDataNumber,
            V9Field::IpProtocolVersion => FieldDataType::UnsignedDataNumber,
            V9Field::Direction => FieldDataType::UnsignedDataNumber,
            V9Field::Ipv6NextHop => FieldDataType::Ip6Addr,
            V9Field::BgpIpv6NextHop => FieldDataType::Ip6Addr,
            V9Field::Ipv6OptionHeaders => FieldDataType::Ipv6ExtensionHeaders,
            V9Field::MplsLabel1
            | V9Field::MplsLabel2
            | V9Field::MplsLabel3
            | V9Field::MplsLabel4
            | V9Field::MplsLabel5
            | V9Field::MplsLabel6
            | V9Field::MplsLabel7
            | V9Field::MplsLabel8
            | V9Field::MplsLabel9
            | V9Field::MplsLabel10 => FieldDataType::UnsignedDataNumber,
            V9Field::InDstMac => FieldDataType::MacAddr,
            V9Field::OutSrcMac => FieldDataType::MacAddr,
            V9Field::IfName => FieldDataType::String,
            V9Field::IfDesc => FieldDataType::String,
            V9Field::SamplerName => FieldDataType::String,
            V9Field::InPermanentBytes => FieldDataType::UnsignedDataNumber,
            V9Field::InPermanentPkts => FieldDataType::UnsignedDataNumber,
            V9Field::FragmentOffset => FieldDataType::UnsignedDataNumber,
            V9Field::ForwardingStatus => FieldDataType::ForwardingStatus,
            V9Field::MplsPalRd => FieldDataType::Vec,
            V9Field::MplsPrefixLen => FieldDataType::UnsignedDataNumber,
            V9Field::SrcTrafficIndex => FieldDataType::UnsignedDataNumber,
            V9Field::DstTrafficIndex => FieldDataType::UnsignedDataNumber,
            V9Field::ApplicationDescription => FieldDataType::String,
            V9Field::ApplicationTag => FieldDataType::Vec,
            V9Field::ApplicationName => FieldDataType::String,
            V9Field::PostipDiffServCodePoint => FieldDataType::UnsignedDataNumber,
            V9Field::Replicationfactor => FieldDataType::UnsignedDataNumber,
            V9Field::Deprecated => FieldDataType::UnsignedDataNumber,
            V9Field::Layer2packetSectionOffset => FieldDataType::UnsignedDataNumber,
            V9Field::Layer2packetSectionSize => FieldDataType::UnsignedDataNumber,
            V9Field::Layer2packetSectionData => FieldDataType::Vec,
            V9Field::BgpNextAdjacentAsNumber => FieldDataType::UnsignedDataNumber,
            V9Field::BgpPrevAdjacentAsNumber => FieldDataType::UnsignedDataNumber,
            V9Field::ExporterIpv4Address => FieldDataType::Ip4Addr,
            V9Field::ExporterIpv6Address => FieldDataType::Ip6Addr,
            V9Field::DroppedOctetDeltaCount => FieldDataType::UnsignedDataNumber,
            V9Field::DroppedPacketDeltaCount => FieldDataType::UnsignedDataNumber,
            V9Field::DroppedOctetTotalCount => FieldDataType::UnsignedDataNumber,
            V9Field::DroppedPacketTotalCount => FieldDataType::UnsignedDataNumber,
            V9Field::FlowEndReason => FieldDataType::FlowEndReason,
            V9Field::CommonPropertiesId => FieldDataType::UnsignedDataNumber,
            V9Field::ObservationPointId => FieldDataType::UnsignedDataNumber,
            V9Field::IcmpTypeCodeIpv6 => FieldDataType::UnsignedDataNumber,
            V9Field::MplsTopLabelIpv6Address => FieldDataType::Ip6Addr,
            V9Field::LineCardId => FieldDataType::UnsignedDataNumber,
            V9Field::PortId => FieldDataType::UnsignedDataNumber,
            V9Field::MeteringProcessId => FieldDataType::UnsignedDataNumber,
            V9Field::ExportingProcessId => FieldDataType::UnsignedDataNumber,
            V9Field::TemplateId => FieldDataType::UnsignedDataNumber,
            V9Field::WlanChannelId => FieldDataType::UnsignedDataNumber,
            V9Field::WlanSsid => FieldDataType::String,
            V9Field::FlowId => FieldDataType::UnsignedDataNumber,
            V9Field::ObservationDomainId => FieldDataType::UnsignedDataNumber,
            V9Field::FlowStartSeconds => FieldDataType::DurationSeconds,
            V9Field::FlowEndSeconds => FieldDataType::DurationSeconds,
            V9Field::FlowStartMilliseconds => FieldDataType::DurationMillis,
            V9Field::FlowEndMilliseconds => FieldDataType::DurationMillis,
            V9Field::FlowStartMicroseconds => FieldDataType::DurationMicrosNTP,
            V9Field::FlowEndMicroseconds => FieldDataType::DurationMicrosNTP,
            V9Field::FlowStartNanoseconds => FieldDataType::DurationNanosNTP,
            V9Field::FlowEndNanoseconds => FieldDataType::DurationNanosNTP,
            V9Field::FlowStartDeltaMicroseconds => FieldDataType::UnsignedDataNumber,
            V9Field::FlowEndDeltaMicroseconds => FieldDataType::UnsignedDataNumber,
            V9Field::SystemInitTimeMilliseconds => FieldDataType::DurationMillis,
            V9Field::FlowDurationMilliseconds => FieldDataType::UnsignedDataNumber,
            V9Field::FlowDurationMicroseconds => FieldDataType::UnsignedDataNumber,
            V9Field::ObservedFlowTotalCount => FieldDataType::UnsignedDataNumber,
            V9Field::IgnoredPacketTotalCount => FieldDataType::UnsignedDataNumber,
            V9Field::IgnoredOctetTotalCount => FieldDataType::UnsignedDataNumber,
            V9Field::NotSentFlowTotalCount => FieldDataType::UnsignedDataNumber,
            V9Field::NotSentPacketTotalCount => FieldDataType::UnsignedDataNumber,
            V9Field::NotSentOctetTotalCount => FieldDataType::UnsignedDataNumber,
            V9Field::DestinationIpv6Prefix => FieldDataType::Ip6Addr,
            V9Field::SourceIpv6Prefix => FieldDataType::Ip6Addr,
            V9Field::PostOctetTotalCount => FieldDataType::UnsignedDataNumber,
            V9Field::PostPacketTotalCount => FieldDataType::UnsignedDataNumber,
            V9Field::FlowKeyIndicator => FieldDataType::UnsignedDataNumber,
            V9Field::PostMcastPacketTotalCount => FieldDataType::UnsignedDataNumber,
            V9Field::PostMcastOctetTotalCount => FieldDataType::UnsignedDataNumber,
            V9Field::IcmpTypeValue => FieldDataType::UnsignedDataNumber,
            V9Field::IcmpCodeValue => FieldDataType::UnsignedDataNumber,
            V9Field::IcmpIpv6TypeValue => FieldDataType::UnsignedDataNumber,
            V9Field::IcmpIpv6CodeValue => FieldDataType::UnsignedDataNumber,
            V9Field::PostNATSourceIPv4Address => FieldDataType::Ip4Addr,
            V9Field::PostNATDestinationIPv4Address => FieldDataType::Ip4Addr,
            V9Field::PostNATTSourceTransportPort => FieldDataType::UnsignedDataNumber,
            V9Field::PostNATTDestinationTransportPort => FieldDataType::UnsignedDataNumber,
            V9Field::PostNATSourceIpv6Address => FieldDataType::Ip6Addr,
            V9Field::PostNATDestinationIpv6Address => FieldDataType::Ip6Addr,
            V9Field::ObservationTimeMilliseconds => FieldDataType::DurationMillis,
            V9Field::NatEvent => FieldDataType::NatEvent,
            _ => FieldDataType::Unknown,
        }
    }
}

impl From<u16> for V9Field {
    fn from(item: u16) -> Self {
        match item {
            1 => V9Field::InBytes,
            2 => V9Field::InPkts,
            3 => V9Field::Flows,
            4 => V9Field::Protocol,
            5 => V9Field::SrcTos,
            6 => V9Field::TcpFlags,
            7 => V9Field::L4SrcPort,
            8 => V9Field::Ipv4SrcAddr,
            9 => V9Field::SrcMask,
            10 => V9Field::InputSnmp,
            11 => V9Field::L4DstPort,
            12 => V9Field::Ipv4DstAddr,
            13 => V9Field::DstMask,
            14 => V9Field::OutputSnmp,
            15 => V9Field::Ipv4NextHop,
            16 => V9Field::SrcAs,
            17 => V9Field::DstAs,
            18 => V9Field::BgpIpv4NextHop,
            19 => V9Field::MulDstPkts,
            20 => V9Field::MulDstBytes,
            21 => V9Field::LastSwitched,
            22 => V9Field::FirstSwitched,
            23 => V9Field::OutBytes,
            24 => V9Field::OutPkts,
            25 => V9Field::MinPktLngth,
            26 => V9Field::MaxPktLngth,
            27 => V9Field::Ipv6SrcAddr,
            28 => V9Field::Ipv6DstAddr,
            29 => V9Field::Ipv6SrcMask,
            30 => V9Field::Ipv6DstMask,
            31 => V9Field::Ipv6FlowLabel,
            32 => V9Field::IcmpType,
            33 => V9Field::MulIgmpType,
            34 => V9Field::SamplingInterval,
            35 => V9Field::SamplingAlgorithm,
            36 => V9Field::FlowActiveTimeout,
            37 => V9Field::FlowInactiveTimeout,
            38 => V9Field::EngineType,
            39 => V9Field::EngineId,
            40 => V9Field::TotalBytesExp,
            41 => V9Field::TotalPktsExp,
            42 => V9Field::TotalFlowsExp,
            43 => V9Field::Vendor,
            44 => V9Field::Ipv4SrcPrefix,
            45 => V9Field::Ipv4DstPrefix,
            46 => V9Field::MplsTopLabelType,
            47 => V9Field::MplsTopLabelIpAddr,
            48 => V9Field::FlowSamplerId,
            49 => V9Field::FlowSamplerMode,
            50 => V9Field::FlowSamplerRandomInterval,
            51 => V9Field::Vendor,
            52 => V9Field::MinTtl,
            53 => V9Field::MaxTtl,
            54 => V9Field::Ipv4Ident,
            55 => V9Field::DstTos,
            56 => V9Field::InSrcMac,
            57 => V9Field::OutDstMac,
            58 => V9Field::SrcVlan,
            59 => V9Field::DstVlan,
            60 => V9Field::IpProtocolVersion,
            61 => V9Field::Direction,
            62 => V9Field::Ipv6NextHop,
            63 => V9Field::BgpIpv6NextHop,
            64 => V9Field::Ipv6OptionHeaders,
            65 => V9Field::Vendor,
            66 => V9Field::Vendor,
            67 => V9Field::Vendor,
            68 => V9Field::Vendor,
            69 => V9Field::Vendor,
            70 => V9Field::MplsLabel1,
            71 => V9Field::MplsLabel2,
            72 => V9Field::MplsLabel3,
            73 => V9Field::MplsLabel4,
            74 => V9Field::MplsLabel5,
            75 => V9Field::MplsLabel6,
            76 => V9Field::MplsLabel7,
            77 => V9Field::MplsLabel8,
            78 => V9Field::MplsLabel9,
            79 => V9Field::MplsLabel10,
            80 => V9Field::InDstMac,
            81 => V9Field::OutSrcMac,
            82 => V9Field::IfName,
            83 => V9Field::IfDesc,
            84 => V9Field::SamplerName,
            85 => V9Field::InPermanentBytes,
            86 => V9Field::InPermanentPkts,
            87 => V9Field::Vendor,
            88 => V9Field::FragmentOffset,
            89 => V9Field::ForwardingStatus,
            90 => V9Field::MplsPalRd,
            91 => V9Field::MplsPrefixLen,
            92 => V9Field::SrcTrafficIndex,
            93 => V9Field::DstTrafficIndex,
            94 => V9Field::ApplicationDescription,
            95 => V9Field::ApplicationTag,
            96 => V9Field::ApplicationName,
            98 => V9Field::PostipDiffServCodePoint,
            99 => V9Field::Replicationfactor,
            100 => V9Field::Deprecated,
            102 => V9Field::Layer2packetSectionOffset,
            103 => V9Field::Layer2packetSectionSize,
            104 => V9Field::Layer2packetSectionData,
            128 => V9Field::BgpNextAdjacentAsNumber,
            129 => V9Field::BgpPrevAdjacentAsNumber,
            130 => V9Field::ExporterIpv4Address,
            131 => V9Field::ExporterIpv6Address,
            132 => V9Field::DroppedOctetDeltaCount,
            133 => V9Field::DroppedPacketDeltaCount,
            134 => V9Field::DroppedOctetTotalCount,
            135 => V9Field::DroppedPacketTotalCount,
            136 => V9Field::FlowEndReason,
            137 => V9Field::CommonPropertiesId,
            138 => V9Field::ObservationPointId,
            139 => V9Field::IcmpTypeCodeIpv6,
            140 => V9Field::MplsTopLabelIpv6Address,
            141 => V9Field::LineCardId,
            142 => V9Field::PortId,
            143 => V9Field::MeteringProcessId,
            144 => V9Field::ExportingProcessId,
            145 => V9Field::TemplateId,
            146 => V9Field::WlanChannelId,
            147 => V9Field::WlanSsid,
            148 => V9Field::FlowId,
            149 => V9Field::ObservationDomainId,
            150 => V9Field::FlowStartSeconds,
            151 => V9Field::FlowEndSeconds,
            152 => V9Field::FlowStartMilliseconds,
            153 => V9Field::FlowEndMilliseconds,
            154 => V9Field::FlowStartMicroseconds,
            155 => V9Field::FlowEndMicroseconds,
            156 => V9Field::FlowStartNanoseconds,
            157 => V9Field::FlowEndNanoseconds,
            158 => V9Field::FlowStartDeltaMicroseconds,
            159 => V9Field::FlowEndDeltaMicroseconds,
            160 => V9Field::SystemInitTimeMilliseconds,
            161 => V9Field::FlowDurationMilliseconds,
            162 => V9Field::FlowDurationMicroseconds,
            163 => V9Field::ObservedFlowTotalCount,
            164 => V9Field::IgnoredPacketTotalCount,
            165 => V9Field::IgnoredOctetTotalCount,
            166 => V9Field::NotSentFlowTotalCount,
            167 => V9Field::NotSentPacketTotalCount,
            168 => V9Field::NotSentOctetTotalCount,
            169 => V9Field::DestinationIpv6Prefix,
            170 => V9Field::SourceIpv6Prefix,
            171 => V9Field::PostOctetTotalCount,
            172 => V9Field::PostPacketTotalCount,
            173 => V9Field::FlowKeyIndicator,
            174 => V9Field::PostMcastPacketTotalCount,
            175 => V9Field::PostMcastOctetTotalCount,
            176 => V9Field::IcmpTypeValue,
            177 => V9Field::IcmpCodeValue,
            178 => V9Field::IcmpIpv6TypeValue,
            179 => V9Field::IcmpIpv6CodeValue,
            225 => V9Field::PostNATSourceIPv4Address,
            226 => V9Field::PostNATDestinationIPv4Address,
            227 => V9Field::PostNATTSourceTransportPort,
            228 => V9Field::PostNATTDestinationTransportPort,
            230 => V9Field::NatEvent,
            281 => V9Field::PostNATSourceIpv6Address,
            282 => V9Field::PostNATDestinationIpv6Address,
            323 => V9Field::ObservationTimeMilliseconds,
            _ => V9Field::Unknown,
        }
    }
}

#[cfg(test)]
mod v9_lookup_tests {

    use crate::variable_versions::field_value::FieldDataType;

    use super::V9Field;

    use insta::assert_yaml_snapshot;

    #[test]
    fn it_tests_field_lookup() {
        let mut fields = vec![];
        for i in 1..=282 {
            let field: V9Field = i.into();
            fields.push(field);
        }
        assert_yaml_snapshot!(fields);
    }

    #[test]
    fn it_tests_field_data_type_lookup() {
        let mut fields: Vec<FieldDataType> = vec![];
        for i in 1..=282 {
            let field: V9Field = i.into();
            fields.push(field.into());
        }
        assert_yaml_snapshot!(fields);
    }
}
