use nom_derive::*;
use serde::Serialize;

#[repr(u16)]
#[derive(Default, Debug, PartialEq, Eq, Clone, Copy, Serialize, Nom)]
pub enum ScopeFieldType {
    System = 1,
    Interface = 2,
    LineCard = 3,
    NetflowCache = 4,
    Template = 5,
    #[default]
    Unknown = 0,
}

#[repr(u8)]
#[derive(Debug, PartialEq, Eq, Clone, Copy, Serialize, Nom)]
pub enum ForwaringStatus {
    Unknown = 0,
}

#[repr(u16)]
#[derive(Debug, PartialEq, Eq, Clone, Copy, Serialize, Nom)]
pub enum DataFieldType {
    INBYTES = 1,
    INPKTS = 2,
    FLOWS = 3,
    PROTOCOL = 4,
    SRCTOS = 5,
    TCPFLAGS = 6,
    L4SRCPORT = 7,
    IPV4SRCADDR = 8,
    SRCMASK = 9,
    INPUTSNMP = 10,
    L4DSTPORT = 11,
    IPV4DSTADDR = 12,
    DSTMASK = 13,
    OUTPUTSNMP = 14,
    IPV4NEXTHOP = 15,
    SRCAS = 16,
    DSTAS = 17,
    BGPIPV4NEXTHOP = 18,
    MULDSTPKTS = 19,
    MULDSTBYTES = 20,
    LASTSWITCHED = 21,
    FIRSTSWITCHED = 22,
    OUTBYTES = 23,
    OUTPKTS = 24,
    MINPKTLNGTH = 25,
    MAXPKTLNGTH = 26,
    IPV6SRCADDR = 27,
    IPV6DSTADDR = 28,
    IPV6SRCMASK = 29,
    IPV6DSTMASK = 30,
    IPV6FLOWLABEL = 31,
    ICMPTYPE = 32,
    MULIGMPTYPE = 33,
    SAMPLINGINTERVAL = 34,
    SAMPLINGALGORITHM = 35,
    FLOWACTIVETIMEOUT = 36,
    FLOWINACTIVETIMEOUT = 37,
    ENGINETYPE = 38,
    ENGINEID = 39,
    TOTALBYTESEXP = 40,
    TOTALPKTSEXP = 41,
    TOTALFLOWSEXP = 42,
    IPV4SRCPREFIX = 44,
    IPV4DSTPREFIX = 45,
    MPLSTOPLABELTYPE = 46,
    MPLSTOPLABELIPADDR = 47,
    FLOWSAMPLERID = 48,
    FLOWSAMPLERMODE = 49,
    FLOWSAMPLERRANDOMINTERVAL = 50,
    MINTTL = 52,
    MAXTTL = 53,
    IPV4IDENT = 54,
    DSTTOS = 55,
    INSRCMAC = 56,
    OUTDSTMAC = 57,
    SRCVLAN = 58,
    DSTVLAN = 59,
    IPPROTOCOLVERSION = 60,
    DIRECTION = 61,
    IPV6NEXTHOP = 62,
    BPGIPV6NEXTHOP = 63,
    IPV6OPTIONHEADERS = 64,
    MPLSLABEL1 = 70,
    MPLSLABEL2 = 71,
    MPLSLABEL3 = 72,
    MPLSLABEL4 = 73,
    MPLSLABEL5 = 74,
    MPLSLABEL6 = 75,
    MPLSLABEL7 = 76,
    MPLSLABEL8 = 77,
    MPLSLABEL9 = 78,
    MPLSLABEL10 = 79,
    INDSTMAC = 80,
    OUTSRCMAC = 81,
    IFNAME = 82,
    IFDESC = 83,
    SAMPLERNAME = 84,
    INPERMANENTBYTES = 85,
    INPERMANENTPKTS = 86,
    FRAGMENTOFFSET = 87,
    FORWARDINGSTATUS = 88,
    MPLSPALRD = 90,
    MPLSPREFIXLEN = 91,
    SRCTRAFFICINDEX = 92,
    DSTTRAFFICINDEX = 93,
    APPLICATIONDESCRIPTION = 94,
    APPLICATIONTAG = 95,
    APPLICATIONNAME = 96,
    PostipDiffServCodePoint = 98,
    ReplicationFactor = 99,
    DEPRECATED = 100,
    Layer2packetSectionOffset = 102,
    Layer2packetSectionSize = 103,
    Layer2packetSectionData = 104,
    Unknown,
}
